"""
JEE Topics Generator for StudentTools.cyou
Target: 240 distinct, high-quality, practical topics across:
1. Marks & Scoring (40)
2. Percentile & Normalization (45)
3. Rank & Estimations (35)
4. College Prediction & Cutoffs (60)
5. Exam Planning & Countdown (35)
6. Marks Calculator & Accuracy (25)
"""

def get_jee_topics():
    topics = []
    
    # -------------------------------------------------------------
    # 1. Marks & Scoring (40 topics)
    # -------------------------------------------------------------
    ms = [
        ("How JEE Main Negative Marking Affects Your Total Score",
         "Explanation", "Educational", "jee main negative marking",
         "jee marking scheme, negative marking impact, jee scoring rules, 4 marks minus 1",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Analyze how +4 for correct and -1 for incorrect creates non-linear scoring risks. Show numerical examples comparing aggressive guessing vs selective attempts, and illustrate net score calculations with the JEE Marks Calculator.",
         "YES", "HIGH"),
        ("How to Calculate Raw Score from JEE Main Response Sheet",
         "How-To", "How-To", "how to calculate jee main raw score",
         "jee response sheet calculation, nta answer key marks, jee raw marks formula",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Step-by-step guide to downloading NTA response sheet, cross-referencing provisional answer keys, tracking bonus questions, and tallying marks accurately.",
         "YES", "HIGH"),
        ("Why Do Different Shifts Need Different Marks for 99 Percentile in JEE Main?",
         "Explanation", "Informational", "marks required for 99 percentile jee main shift wise",
         "shift difficulty marks 99 percentile, jee shift variation, easy vs hard shift jee score",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain shift-wise variance where an easy shift requires 210+ marks while a tough shift requires 165 marks for 99 percentile due to raw score distributions.",
         "YES", "HIGH"),
        ("JEE Main Section B Numerical Questions: Marking Scheme and Penalty Rules",
         "Guide", "Reference", "jee main section b marking scheme",
         "jee numerical questions negative marking, section b rules, integer questions jee main",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Detail the evolution of Section B numerical questions, negative marking introduction, rounding off guidelines, and score calculation nuances.",
         "YES", "MEDIUM"),
        ("Impact of Unattempted Questions vs Incorrect Answers in JEE Main",
         "Comparison", "Comparison", "unattempted vs negative marking jee main",
         "jee guessing penalty, unattempted marks jee, risk analysis jee questions",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Compare two hypothetical students attempting 50 questions vs 65 questions with varying error rates, demonstrating why wild guesses degrade ranks.",
         "YES", "HIGH"),
        ("How Dropped and Bonus Questions Affect JEE Main Marks Calculation",
         "Explanation", "Educational", "jee main dropped questions marks rule",
         "nta bonus question rule, dropped question scoring, marks for all candidates jee",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Clarify NTA official policy on dropped questions: differences between MCQs and numerical questions, and how raw score scaling applies across shifts.",
         "YES", "MEDIUM"),
        ("How to Challenge Provisional Answer Key in JEE Main: Fee and Scoring Rules",
         "Guide", "How-To", "how to challenge jee main answer key",
         "nta answer key challenge process, fee refund answer key challenge, marks revision jee",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain the NTA challenge procedure, non-refundable processing fee, expert committee review, and how revised final answer keys impact marks tally.",
         "YES", "MEDIUM"),
        ("Understanding the Tie-Breaking Criteria in JEE Main Scorecards",
         "Guide", "Reference", "jee main tie breaking rule",
         "tie breaking criteria nta, mathematics score tie breaker, age criteria jee main tie",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Break down the sequential tie-breaking protocol: Math percentile, Physics percentile, Chemistry percentile, ratio of positive to negative attempts, and age.",
         "YES", "HIGH"),
        ("How to Determine Target Raw Score for Top 10 NITs",
         "Planning Guide", "Planning", "marks needed for top nits in jee main",
         "raw score for nit trichy, marks for cse in top nits, safe score for nit",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Examine historical score trends across tough, moderate, and easy exam papers to define safe score ranges for premier NIT branches.",
         "YES", "HIGH"),
        ("What Does a Negative Total Score Mean in JEE Main?",
         "Explanation", "Informational", "can jee main score be negative",
         "negative marks in jee main, minus score jee scorecard, negative percentile myth",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain how raw scores can drop below zero due to heavy negative marking, while percentile scores remain positive (strictly between 0 and 100).",
         "YES", "LOW"),
        ("Formula for JEE Main Raw Score: Step-by-Step Breakdown with Examples",
         "Formula Guide", "How-To", "jee main score formula",
         "calculate marks in jee, formula for jee raw score, correct incorrect unanswered formula",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Provide the exact formula: Score = (Correct * 4) - (Incorrect * 1) + (Unattempted * 0). Provide worked examples for varying attempt distributions.",
         "YES", "HIGH"),
        ("How Accuracy Percentage Determines Final Score in JEE Main",
         "Guide", "Educational", "accuracy percentage in jee main",
         "jee exam accuracy, calculation errors jee main, negative marking reduction",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Demonstrate mathematical model showing how an increase in accuracy from 70% to 88% drastically elevates net marks even with fewer questions attempted.",
         "YES", "HIGH"),
        ("Strategic Elimination: How to Convert 50-50 Choices into Positive Expected Marks",
         "Guide", "Planning", "intelligent guessing in jee main",
         "eliminating options jee main, probability guessing jee, positive expectation guessing",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Evaluate statistical expectation of guessing: +4 * 0.5 - 1 * 0.5 = +1.5 expected return when eliminating two options vs wild 4-choice guess (-0.25 return).",
         "YES", "HIGH"),
        ("How Chemistry Scoring Efficiency Compares to Mathematics in JEE Main",
         "Comparison", "Educational", "chemistry vs maths scoring jee main",
         "chemistry marks per minute, scoring fast in chemistry, math time sink jee",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Compare time investment per mark between Chemistry (often 1.5 marks per minute) and Mathematics (0.6 marks per minute) and score optimization strategies.",
         "YES", "MEDIUM"),
        ("Physics Scoring Trends in JEE Main: Formula Application vs Conceptual Questions",
         "Explanation", "Informational", "physics marks trends jee main",
         "easy physics high cutoff jee, formula based physics scoring, physics marks to percentile",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Analyze why recent JEE Main sessions saw high physics averages and why scoring 80+ in Physics has become necessary for 99 overall percentile.",
         "YES", "MEDIUM"),
        ("Subject-Wise Minimum Marks vs Overall JEE Main Percentile",
         "Guide", "Reference", "is there subject wise cutoff in jee main",
         "jee main sectional cutoff, subject minimum marks jee, nta sectional rules",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Clarify that JEE Main does NOT have sectional minimum cutoff marks for rank generation, contrasting it with JEE Advanced rules.",
         "YES", "HIGH"),
        ("How Mock Test Scores Compare to Actual JEE Main Exam Marks",
         "Comparison", "Comparison", "mock test vs actual jee main marks",
         "allen resonance mock marks vs jee, coaching test score comparison, jee actual score prediction",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Compare test series difficulty calibrations with actual NTA papers, highlighting normalization factors and psychological exam day swings.",
         "YES", "MEDIUM"),
        ("Why Raw Score Is Never Printed on the Official JEE Main Rank Card",
         "Explanation", "Informational", "why raw marks not shown in jee scorecard",
         "nta scorecard format, nta score vs raw marks, percentile only on jee marksheet",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain why NTA issues only multi-session normalized NTA scores (percentiles up to 7 decimal places) to prevent raw score discrimination across shifts.",
         "YES", "MEDIUM"),
        ("Does Attempting More Questions Always Increase Your JEE Main Score?",
         "Explanation", "Educational", "should i attempt more questions in jee main",
         "optimal number of questions to attempt jee, high attempts vs high accuracy, safe attempt count",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Mathematical proof demonstrating diminishing returns and score deterioration when candidates over-attempt beyond their mastery zone.",
         "YES", "HIGH"),
        ("How Question Selection Strategy Dictates Your Final JEE Main Raw Score",
         "Guide", "Planning", "question selection strategy jee main",
         "round 1 round 2 question solving, 3 pass method jee, scoring easy questions first",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain the 3-round examination strategy: picking low-hanging easy questions first, moderate calculations second, and tough time-sinks last.",
         "YES", "HIGH"),
    ]

    # Add 20 marks milestone topics
    marks_list = [
        (50, "50 Marks in JEE Main: Percentile Range and Qualifying Prospects", "50 marks in jee main percentile", "LOW"),
        (70, "70 Marks in JEE Main: Category Qualifying Cutoffs and Options", "70 marks in jee main percentile", "LOW"),
        (90, "90 Marks in JEE Main: Percentile Band and College Opportunities", "90 marks in jee main percentile", "MEDIUM"),
        (100, "100 Marks in JEE Main: Shift-Wise Percentile and College Prospects", "100 marks in jee main percentile", "MEDIUM"),
        (110, "110 Marks in JEE Main: Expected Percentile and State College Cutoffs", "110 marks in jee main percentile", "MEDIUM"),
        (120, "120 Marks in JEE Main: Percentile Range and Eligible Engineering Colleges", "120 marks in jee main percentile", "MEDIUM"),
        (130, "130 Marks in JEE Main: Percentile Forecast and Mid-Tier NIT Branches", "130 marks in jee main percentile", "HIGH"),
        (140, "140 Marks in JEE Main: Expected Percentile and NIT Admission Prospects", "140 marks in jee main percentile", "HIGH"),
        (150, "Is 150 Marks in JEE Main Enough for NITs? Shift-Wise Analysis", "150 marks in jee main percentile", "HIGH"),
        (160, "160 Marks in JEE Main: What Percentile Can You Get Across Shifts?", "160 marks in jee main percentile", "HIGH"),
        (170, "170 Marks in JEE Main: Approaching the 98 Percentile Mark", "170 marks in jee main percentile", "HIGH"),
        (180, "180 Marks in JEE Main: Can You Cross the 98.5 Percentile Barrier?", "180 marks in jee main percentile", "HIGH"),
        (190, "190 Marks in JEE Main: Expected Percentile and Top 10 NIT Core Branches", "190 marks in jee main percentile", "HIGH"),
        (200, "200 Marks in JEE Main: Target Percentile and Top NIT Branch Opportunities", "200 marks in jee main percentile", "HIGH"),
        (210, "210 Marks in JEE Main: Breaking into 99.2+ Percentile Club", "210 marks in jee main percentile", "HIGH"),
        (220, "220 Marks in JEE Main: Expected Percentile and Top 5 NIT CSE Chances", "220 marks in jee main percentile", "HIGH"),
        (230, "230 Marks in JEE Main: Pathway to 99.5+ Percentile and Under 5000 Rank", "230 marks in jee main percentile", "HIGH"),
        (240, "240+ Marks in JEE Main: Road to 99.7+ Percentile and Elite NIT Seats", "240 marks in jee main percentile", "HIGH"),
        (250, "250 Marks in JEE Main: Securing Top 2000 All India Rank", "250 marks in jee main percentile", "HIGH"),
        (270, "270+ Marks in JEE Main: What Does It Take to Reach the 99.9 Percentile?", "270 marks in jee main percentile", "HIGH"),
    ]
    for marks, title, kw, prio in marks_list:
        ms.append((
            title, "Explanation", "Educational", kw,
            f"{marks} marks jee main, {marks} score percentile, marks vs percentile {marks}",
            "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
            f"Analyze expected percentile bands across tough, moderate, and easy shifts for a raw score of {marks} marks, explaining candidate competition and college opportunities.",
            "YES", prio
        ))

    for item in ms:
        topics.append({
            "topic": item[0], "category": "JEE", "topic_cluster": "Marks & Scoring",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 2. Percentile & Normalization (45 topics)
    # -------------------------------------------------------------
    perc = [
        ("How NTA Normalization Formula Works in JEE Main: Complete Mathematical Guide",
         "Formula Guide", "Educational", "how nta normalization works in jee main",
         "nta percentile formula, jee normalization process, normal distribution jee main score",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Dissect NTA official percentile formula: 100 * (Number of candidates appeared in session with raw score <= candidate) / Total candidates in session. Explain 7 decimal places.",
         "YES", "HIGH"),
        ("Difference Between Percentage and Percentile in JEE Main Scorecard",
         "Comparison", "Educational", "percentage vs percentile in jee main",
         "percentile meaning in jee, is 90 percentile equal to 90 percent, jee marks percentage vs percentile",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Clarify the critical distinction: percentage represents marks scored out of maximum marks (300), while percentile represents relative ranking against peers in your session.",
         "YES", "HIGH"),
        ("Why Does NTA Calculate JEE Main Percentile Up to 7 Decimal Places?",
         "Explanation", "Informational", "why jee percentile has 7 decimal places",
         "7 decimal places nta score, tie breaking decimals jee, percentile precision nta",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain how with 12 to 14 lakh candidates, 7 decimals are mathematically necessary to distinguish individual candidates and avoid thousands of rank ties.",
         "YES", "MEDIUM"),
        ("How to Interpret Your NTA Scorecard: Session 1 vs Session 2 Best Score Rule",
         "Guide", "How-To", "how nta combines session 1 and session 2 scores",
         "best of two sessions jee, jee final percentile calculation, combined scorecard nta",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain how NTA merges Session 1 and Session 2 percentiles, taking the best overall percentile for CRL generation, not the average.",
         "YES", "HIGH"),
        ("Can Your JEE Main Percentile Decrease in Session 2?",
         "Explanation", "Informational", "can jee percentile decrease in session 2",
         "does session 2 lower your rank, best score rule jee, appearing in both sessions jee",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Reassure students that appearing in Session 2 carries zero downside risk because only their best NTA score is considered for final merit rank.",
         "YES", "HIGH"),
        ("What Does 99 Percentile Mean in JEE Main in Terms of Candidates and Rank?",
         "Explanation", "Educational", "what is 99 percentile in jee main",
         "how many students get 99 percentile, rank for 99 percentile jee, marks needed for 99 percentile",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Calculate the top 1% cohort out of ~12 lakh test-takers (~12,000 rank), college options available, and required raw score ranges.",
         "YES", "HIGH"),
        ("Understanding the Difference Between Subject Percentile and Total Percentile",
         "Explanation", "Educational", "subject percentile vs total percentile jee",
         "why total percentile is not average of subjects, physics maths chemistry percentile, nta composite score",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain why total NTA percentile is calculated independently based on total composite marks and is NOT the arithmetic average of PCM percentiles.",
         "YES", "HIGH"),
        ("How Tough Shifts Benefit Students in JEE Main Normalization",
         "Explanation", "Educational", "does tough shift help in jee normalization",
         "easiest vs toughest shift percentile, shift normalization advantage, jee tough paper percentile boost",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain how low session averages in difficult papers mean that even 170 marks can yield a 99.2 percentile, whereas in easy papers 210 might be needed.",
         "YES", "MEDIUM"),
        ("Why Do Two Candidates with the Same Raw Marks Get Different Percentiles?",
         "Explanation", "Educational", "same marks different percentile jee main",
         "shift difference jee marks, normalization shift disparity, raw score variance across days",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Illustrate with concrete example: candidate A scoring 180 in Jan 27 shift 1 vs candidate B scoring 180 in Jan 31 shift 2, showing how peer distributions determine percentile.",
         "YES", "HIGH"),
        ("Percentile Inflation in JEE Main: What Causes It and How to Plan for It",
         "Explanation", "Informational", "jee main percentile inflation",
         "why cutoff percentiles rise, more candidates appearing jee, percentile competition trends",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Analyze how increasing candidate counts (from 9 lakhs to 12+ lakhs) increases the absolute number of candidates ahead of any given percentile value.",
         "YES", "MEDIUM"),
        ("What Does a 100 Percentile in JEE Main Represent?",
         "Explanation", "Informational", "100 percentile in jee main meaning",
         "air 1 jee main percentile, how many get 100 percentile, highest marks in jee",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain that 100 percentile represents the session topper who scored higher than or equal to 100% of candidates in that specific shift.",
         "YES", "HIGH"),
        ("How to Estimate Percentile from Expected Marks Before Official Results",
         "How-To", "Planning", "how to estimate jee percentile before result",
         "predicting jee percentile from marks, unofficial answer key percentile, student tools percentile estimator",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Walk through estimating percentile bands using StudentTools Marks to Percentile Estimator based on student feedback on shift difficulty.",
         "YES", "HIGH"),
        ("Why 90 Percentile Does Not Mean You Scored 90% of Total Marks",
         "Explanation", "Educational", "difference between scoring 90 percent and 90 percentile",
         "percentile misconception jee, 90 percentile marks in jee, relative grading jee",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Deconstruct the widespread student and parent myth that 90 percentile requires 270/300 marks; show it often requires only 100-115 marks.",
         "YES", "HIGH"),
        ("Understanding Session-Wise Percentile Cutoffs for JEE Advanced Eligibility",
         "Guide", "Reference", "qualifying percentile for jee advanced",
         "expected cutoff percentile jee advanced, category cutoffs jee advanced, qualifying score nta",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Review the 2.5 lakh candidates qualification rule for JEE Advanced and how category quotas define qualifying percentile cutoffs.",
         "YES", "HIGH"),
        ("How to Compare Your Session 1 and Session 2 Percentiles Effectively",
         "Guide", "How-To", "how to compare session 1 and session 2 marks",
         "tracking jee improvement, did my score improve session 2, comparing normalized scores",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Guide to evaluating real academic progress between sessions by looking past raw marks and focusing on percentile shift and subject accuracy.",
         "YES", "MEDIUM"),
        ("Can JEE Main Percentile Be Zero?",
         "Explanation", "Educational", "can jee percentile be zero",
         "lowest possible percentile jee, minimum percentile nta, percentile bounds",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Demonstrate mathematically why percentile is strictly greater than 0 and up to 100, explaining boundary values in NTA formula.",
         "YES", "LOW"),
        ("Statistical Normalization vs Scaling: How Does JEE Main Differ from Other Exams?",
         "Comparison", "Educational", "jee normalization vs gate normalization",
         "how other exams normalize scores, percentile method vs mean standard deviation, competitive exam normalization",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Compare NTA's pure percentile ranking approach with GATE/CAT mean-and-standard-deviation scaling formulas.",
         "YES", "MEDIUM"),
        ("How Shift Attendance Disparities Impact Percentile Calculations",
         "Explanation", "Educational", "how attendance per shift affects jee percentile",
         "shift size jee main, candidate distribution across shifts, nta shift balancing",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Examine how NTA distributes candidates across exam slots randomly to maintain equal statistical variance and demographic fairness across shifts.",
         "YES", "MEDIUM"),
        ("Why Multiple Sessions Reduce Luck and Shift Bias in JEE Main",
         "Explanation", "Informational", "why two sessions are conducted in jee main",
         "benefits of two attempts jee, reducing bad day effect, fair normalization across multiple sessions",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Explain the educational rationale for providing two attempts: smoothing health or travel emergencies and providing fair normalization.",
         "YES", "LOW"),
        ("How Coaching Institutes Predict JEE Main Percentiles: Accuracy and Limitations",
         "Guide", "Informational", "how accurate are coaching percentile predictors",
         "marks vs percentile prediction accuracy, sample bias in coaching predictors, estimating percentile realistically",
         "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
         "Evaluate why unofficial sample polls have high-score selection bias and how statistical modeling produces realistic ranges.",
         "YES", "MEDIUM"),
    ]

    p_milestones = [
        (99.95, "99.95 Percentile in JEE Main: Marks Needed, Rank, and Top NIT CSE Prospects", "99.95 percentile in jee main", "HIGH"),
        (99.8, "99.8 Percentile in JEE Main: Securing CSE in Top 3 NITs", "99.8 percentile in jee main", "HIGH"),
        (99.5, "99.5 Percentile in JEE Main: Estimated CRL Rank and College Admission Scope", "99.5 percentile in jee main", "HIGH"),
        (99.2, "99.2 Percentile in JEE Main: Top IIIT and NIT Branch Opportunities", "99.2 percentile in jee main", "HIGH"),
        (99.0, "99 Percentile in JEE Main: Rank Range, Safe Marks, and Premier NIT Cutoffs", "99 percentile in jee main", "HIGH"),
        (98.8, "98.8 Percentile in JEE Main: Safe Options for CSE and ECE in NITs", "98.8 percentile in jee main", "HIGH"),
        (98.5, "98.5 Percentile in JEE Main: Rank Estimates and Top IIIT/NIT Choices", "98.5 percentile in jee main", "HIGH"),
        (98.2, "98.2 Percentile in JEE Main: Cutoffs for Premier State and Central Institutes", "98.2 percentile in jee main", "HIGH"),
        (98.0, "98 Percentile in JEE Main: Expected Rank and Eligible Engineering Colleges", "98 percentile in jee main", "HIGH"),
        (97.5, "97.5 Percentile in JEE Main: Core vs Tech Branches in Top 10 NITs", "97.5 percentile in jee main", "HIGH"),
        (97.0, "97 Percentile in JEE Main: Branch Opportunities in Top 15 NITs", "97 percentile in jee main", "HIGH"),
        (96.5, "96.5 Percentile in JEE Main: Good NIT Branches and Established IIITs", "96.5 percentile in jee main", "HIGH"),
        (96.0, "96 Percentile in JEE Main: What Rank and Which NITs Can You Get?", "96 percentile in jee main", "HIGH"),
        (95.5, "95.5 Percentile in JEE Main: Expected Rank and Safe Engineering Branches", "95.5 percentile in jee main", "HIGH"),
        (95.0, "95 Percentile in JEE Main: Safe Options for General, OBC, EWS, SC, and ST", "95 percentile in jee main", "HIGH"),
        (94.5, "94.5 Percentile in JEE Main: Core Engineering Branches in Established NITs", "94.5 percentile in jee main", "MEDIUM"),
        (94.0, "94 Percentile in JEE Main: Which NITs and Branches Are Realistic?", "94 percentile in jee main", "MEDIUM"),
        (93.5, "93.5 Percentile in JEE Main: CSAB Round Prospects and State Government Colleges", "93.5 percentile in jee main", "MEDIUM"),
        (93.0, "93 Percentile in JEE Main: JoSAA vs CSAB Counselling Expectations", "93 percentile in jee main", "MEDIUM"),
        (92.0, "92 Percentile in JEE Main: New IIITs and State Government College Options", "92 percentile in jee main", "MEDIUM"),
        (91.0, "91 Percentile in JEE Main: Category Quotas and Home State Seat Analysis", "91 percentile in jee main", "MEDIUM"),
        (90.0, "90 Percentile in JEE Main: Expected Rank, Qualifying Status, and College Reality", "90 percentile in jee main", "HIGH"),
        (85.0, "85 Percentile in JEE Main: College Options Across Quotas and Alternative Exams", "85 percentile in jee main", "MEDIUM"),
        (80.0, "80 Percentile in JEE Main: Category Cutoffs and State Level Counselling Paths", "80 percentile in jee main", "MEDIUM"),
        (75.0, "75 Percentile in JEE Main: Private Universities and State Engineering Admissions", "75 percentile in jee main", "LOW"),
    ]
    for pval, title, kw, prio in p_milestones:
        perc.append((
            title, "Explanation", "Educational", kw,
            f"{pval} percentile jee rank, {pval} percentile marks, colleges for {pval} percentile",
            "JEE Main Marks to Percentile", "/jee/marks-to-percentile",
            f"Comprehensive breakdown of {pval} percentile: estimated All India Rank, required raw score across shifts, and college branches across NITs, IIITs, and GFTIs.",
            "YES", prio
        ))

    for item in perc:
        topics.append({
            "topic": item[0], "category": "JEE", "topic_cluster": "Percentile",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 3. Rank & Estimations (35 topics)
    # -------------------------------------------------------------
    rnk = [
        ("How to Calculate Your All India Rank (AIR) from JEE Main Percentile",
         "Formula Guide", "How-To", "calculate air from jee main percentile",
         "formula for rank from percentile, jee rank formula, nta percentile to rank conversion",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain the standard formula: Estimated AIR = (100 - Percentile) * (Total Candidates / 100) + 1, showing sample calculations.",
         "YES", "HIGH"),
        ("Difference Between Common Rank List (CRL) and Category Rank in JEE Main",
         "Comparison", "Educational", "crl vs category rank in jee main",
         "what is crl rank, category rank vs open rank, josaa counselling rank used",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Detail how CRL encompasses all candidates across India while Category Rank (OBC-NCL, EWS, SC, ST) ranks candidates within reserved pools.",
         "YES", "HIGH"),
        ("Why Do Two Rank Predictors Give Different Results for the Same Percentile?",
         "Explanation", "Informational", "why do jee rank predictors differ",
         "rank predictor accuracy, total candidates assumption rank predictor, rank calculation discrepancy",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain that variance comes from assumptions regarding total unique test-takers (e.g., 12.5 lakh vs 14 lakh) and tie-breaking estimates.",
         "YES", "HIGH"),
        ("Understanding PwD Category Rank Calculation in JEE Main",
         "Guide", "Reference", "pwd rank in jee main",
         "pwd reservation jee main, horizontal reservation engineering colleges, pwd cutoff ranks",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain horizontal reservation for PwD candidates across General, OBC, EWS, SC, and ST categories and how PwD merit rank functions.",
         "YES", "MEDIUM"),
        ("How Many Candidates Appear in JEE Main Each Year and How It Affects Ranks",
         "Explanation", "Reference", "how many students appear for jee main",
         "total applicants jee main, jee candidate volume trend, competition level jee",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Analyze the multi-year trajectory of unique applicants and explain why higher candidate registration stretches the absolute rank scale.",
         "YES", "HIGH"),
        ("Can Category Rank Be Higher than CRL Rank in JEE Main?",
         "Explanation", "Educational", "can category rank be higher than crl",
         "category rank vs crl number, understanding category merit, jee scorecard ranks explained",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Clear up numerical confusion: category rank is always a smaller number (e.g., Category Rank 1,500 vs CRL 12,000), meaning a better relative position.",
         "YES", "MEDIUM"),
        ("How Unique Candidates Across Both Sessions Impact the Final CRL",
         "Explanation", "Educational", "unique candidates in jee main final rank",
         "session 1 session 2 overlap, unique registration nta, final crl generation process",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain why final All India Ranks are only declared after Session 2 when the total count of unique individual test-takers is finalized.",
         "YES", "HIGH"),
        ("How Tie-Breaking Affects Final All India Rank Allocation",
         "Explanation", "Reference", "how does tie breaking change jee rank",
         "same percentile different rank jee, tie breaker impact air, nta merit allocation",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Detail real situations where candidates with identical overall percentiles receive ranks separated by hundreds of positions due to subject tie-breakers.",
         "YES", "HIGH"),
        ("Rank Range for Getting Computer Science in Top 5 NITs",
         "Guide", "Reference", "rank required for cse in top nits",
         "nit trichy cse closing rank, nit surathkal cse cutoff, closing rank for cse in nits",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Detailed review of closing ranks (AIR 1,000 to AIR 5,000) for Computer Science across NIT Trichy, Surathkal, Warangal, Rourkela, and Calicut.",
         "YES", "HIGH"),
        ("What Is a Safe Rank in JEE Main for General Category in NITs?",
         "Guide", "Reference", "safe rank for general category in nits",
         "maximum closing rank nits general, safe air for nit admission, getting into nit with general rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Comprehensive review showing safe CRL ranks (typically within AIR 40,000-45,000 for other state and up to 60,000 for home state quota).",
         "YES", "HIGH"),
        ("OBC-NCL Rank vs CRL: How Reservation Modifies Admission Chances",
         "Comparison", "Educational", "obc ncl rank vs crl in josaa",
         "obc rank benefits, obc category closing rank nits, crl vs obc rank conversion",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain how JoSAA uses CRL for Open seats and Category rank for Reserved seats, illustrating the seat matrix dual-evaluation process.",
         "YES", "HIGH"),
        ("EWS Category Rank: Trends, Availability, and Cutoff Ranks in JoSAA",
         "Guide", "Reference", "ews category rank cutoffs jee main",
         "ews rank vs crl rank, ews quota benefits nit, ews closing ranks engineering",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Analyze 10% EWS quota allocation, typical ratio between EWS rank and CRL rank (roughly 1:6 to 1:8), and branch impact.",
         "YES", "MEDIUM"),
        ("SC and ST Category Rank Dynamics in Top Engineering Institutes",
         "Guide", "Reference", "sc st rank cutoffs in nits",
         "sc category rank vs crl, st category closing ranks, reservation cutoffs engineering",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain seat allocation dynamics for SC (15%) and ST (7.5%) categories in NITs, IIITs, and GFTIs with representative closing rank milestones.",
         "YES", "MEDIUM"),
        ("Female Supernumerary Quota: How It Lowers Closing Ranks for Girls",
         "Guide", "Reference", "female supernumerary quota in nits",
         "girls quota in jee main, female closing rank difference, 20 percent female quota engineering",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain the 20% female supernumerary seat allocation policy in NITs and IITs, illustrating how female closing ranks compare to gender-neutral ranks.",
         "YES", "HIGH"),
        ("Rank Predictor vs Official NTA Rank: Understanding the Error Margin",
         "Explanation", "Educational", "accuracy of jee rank predictors",
         "rank predictor error margin, why predicted rank changes, trusting rank estimators",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Provide an honest statistical assessment of error margins (+/- 1% to 3%) inherent in any pre-official rank estimator.",
         "YES", "MEDIUM"),
        ("What Rank Is Needed to Qualify for JEE Advanced?",
         "Guide", "Reference", "rank needed to qualify for jee advanced",
         "top 2.5 lakh candidates jee main, qualifying rank advanced, cutoff rank jee advanced",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Break down the category-wise distribution of the top 2,50,000 candidates eligible to sit for JEE Advanced.",
         "YES", "HIGH"),
        ("What Can You Get with a Rank Between 50,000 and 1,00,000 in JEE Main?",
         "Guide", "Educational", "colleges for 50000 to 100000 rank in jee main",
         "gfti admission 75000 rank, state colleges 80000 rank, csab round options 1 lakh rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Realistic roadmap for candidates in the 50k-100k rank band: North-East NITs, established GFTIs, and prominent state government universities.",
         "YES", "HIGH"),
        ("Understanding State Merit Rank vs All India Rank in Engineering Admissions",
         "Comparison", "Educational", "state rank vs all india rank jee main",
         "state engineering counselling rank, dtu nsut state rank, reap jac delhi state rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain how state counselling bodies (JAC Delhi, REAP Rajasthan, HSTES Haryana, UPTAC) convert JEE Main CRL into separate state merit lists.",
         "YES", "HIGH"),
        ("How to Estimate Category Rank from CRL Rank",
         "How-To", "How-To", "how to estimate category rank from crl",
         "crl to obc rank formula, crl to ews rank calculation, category multiplier jee",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Provide historical category distribution multipliers to help students approximate their category rank from estimated CRL rank.",
         "YES", "MEDIUM"),
        ("What Happens If Two Students Get the Exact Same All India Rank?",
         "Explanation", "Educational", "can two students get same rank in jee main",
         "joint ranks in jee, tie resolution nta, what happens in identical rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain NTA's comprehensive multi-stage tie-breaking rules that ensure distinct serial ranks for virtually all candidates.",
         "YES", "LOW"),
        ("How Many Marks Are Needed for AIR Under 1,000 in JEE Main?",
         "Guide", "Reference", "marks needed for top 1000 rank in jee main",
         "air 1000 marks jee, 99.9 percentile marks, score for top 1000 rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Examine historical marks data across shifts showing raw scores typically required (240-270 marks) to crack the top 1,000 AIR barrier.",
         "YES", "HIGH"),
        ("How Many Marks Are Needed for AIR Under 5,000 in JEE Main?",
         "Guide", "Reference", "marks needed for top 5000 rank in jee main",
         "air 5000 marks jee, 99.6 percentile marks, score for top 5000 rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Analyze score trends for securing a top 5,000 position across shifts.",
         "YES", "HIGH"),
        ("How Many Marks Are Needed for AIR Under 10,000 in JEE Main?",
         "Guide", "Reference", "marks needed for top 10000 rank in jee main",
         "air 10000 marks jee main, 99 percentile marks needed, score for 10000 rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Review required marks (typically 185-215 marks depending on shift difficulty) to secure a sub-10,000 rank ensuring premier NIT seats.",
         "YES", "HIGH"),
        ("How Many Marks Are Needed for AIR Under 25,000 in JEE Main?",
         "Guide", "Reference", "marks needed for top 25000 rank in jee main",
         "air 25000 marks jee, 98 percentile marks, rank 25000 score",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Analyze marks requirements (around 160-185 marks) to secure a top 25k position.",
         "YES", "HIGH"),
        ("Why Do JEE Main Cutoff Ranks Fluctuate from Round 1 to Round 6 in JoSAA?",
         "Explanation", "Educational", "why closing ranks change in josaa rounds",
         "round 1 vs round 6 cutoff rank, seat acceptance withdrawal, rank drop josaa",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain the seat upgradation, floating, sliding, and withdrawal mechanics that cause closing ranks to expand across counselling rounds.",
         "YES", "HIGH"),
        ("How CSAB Special Rounds Extend Closing Ranks Beyond JoSAA",
         "Guide", "Reference", "csab special round closing ranks",
         "csab cutoff vs josaa cutoff, vacant seat counselling nit, csab rank jumps",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain how vacant seat reconciliation in CSAB Special Rounds allows candidates with ranks 20,000-50,000 spots lower to secure NIT/IIIT seats.",
         "YES", "HIGH"),
        ("Is It Possible to Get an NIT with 1.5 Lakh Rank in JEE Main?",
         "Guide", "Educational", "can i get nit with 1.5 lakh rank",
         "nit cutoff 150000 rank, home state quota high rank nit, north east nit closing rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explore realistic possibilities: Home State quotas in NIT Mizoram, Nagaland, Sikkim, Srinagar, and reserved category openings.",
         "YES", "HIGH"),
        ("How Does Your JEE Main Rank Affect Non-JoSAA Private College Admissions?",
         "Guide", "Informational", "private colleges accepting jee main rank",
         "thapar lnmiit jee rank, da-iict jee cutoff, nirf top private colleges jee score",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Review premier private universities (Thapar, LNMIIT, DA-IICT, Jaypee, Nirma) that allocate substantial seat shares through JEE Main CRL.",
         "YES", "MEDIUM"),
        ("Understanding the Impact of 12th Board Top 20 Percentile on Rank Validity",
         "Explanation", "Reference", "75 percent criteria vs top 20 percentile",
         "12th board eligibility for nit iit, top 20 percentile state board cutoff, board marks rank condition",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Explain the mandatory 75% aggregate marks (or top 20 percentile in respective 12th board) prerequisite for JEE Main rank-based admissions.",
         "YES", "HIGH"),
        ("How to Track Rank Trends Over the Last 5 Years for Your Dream Branch",
         "How-To", "How-To", "how to analyze previous year josaa cutoffs",
         "tracking closing rank trends, branch popularity trends, josaa historical cutoffs",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Step-by-step guide to downloading and charting JoSAA archival data to spot stable vs fluctuating closing rank patterns.",
         "YES", "MEDIUM"),
        ("What Does a 5-Digit vs 6-Digit Rank Mean for Indian Engineering Aspirants?",
         "Explanation", "Educational", "5 digit vs 6 digit rank in jee main",
         "engineering college options by rank tier, under 50000 rank vs over 1 lakh rank, career planning jee rank",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "A candid structural overview of Indian engineering college tiers mapped to sub-10k, 10k-50k, 50k-100k, and 100k+ rank segments.",
         "YES", "MEDIUM"),
        ("How to Estimate Rank If Only Shift Marks and Unofficial Key Are Known",
         "Guide", "How-To", "estimate rank before jee main result",
         "rough rank estimation from marks, shift difficulty rank prediction, early rank calculation",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "A 3-step synthesis: calculate raw score with Marks Calculator -> map to percentile with Estimator -> convert to estimated CRL rank.",
         "YES", "HIGH"),
        ("Evaluating Closing Rank Jumps Between Core Branches and CSE",
         "Comparison", "Educational", "cse vs core branch closing rank gap",
         "rank difference cse mechanical, branch preference impact rank, engineering cutoff disparity",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Analyze why CSE closing ranks are often 5x to 8x stricter than Civil or Metallurgy within the exact same top-tier NIT.",
         "YES", "MEDIUM"),
        ("How Do Candidate Dropouts Before JoSAA Round 1 Alter Rank Competitiveness?",
         "Explanation", "Informational", "dropouts before josaa counselling",
         "bitsat foreign admissions dropouts, candidate withdrawal effect, effective rank competition",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Examine how high-scoring candidates opting for BITS Pilani, IISc, or international universities ease competition in JoSAA.",
         "YES", "LOW"),
        ("What CRL Rank Is Required for Mechanical Engineering in Top 10 NITs?",
         "Guide", "Reference", "mechanical engineering rank in top 10 nits",
         "nit mechanical closing rank general, mechanical cutoff trichy warangal, safe rank for mechanical",
         "JEE Main Percentile to Rank", "/jee/percentile-to-rank",
         "Review closing ranks ranging from AIR 12,000 at top NITs to AIR 35,000 at mid-tier institutes across categories.",
         "YES", "MEDIUM"),
    ]

    for item in rnk:
        topics.append({
            "topic": item[0], "category": "JEE", "topic_cluster": "Rank",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 4. College Prediction & Cutoffs (60 topics)
    # -------------------------------------------------------------
    clg = [
        ("How JoSAA Counselling Works: Step-by-Step Registration and Choice Filling Guide",
         "Guide", "How-To", "how josaa counselling works",
         "josaa choice filling process, seat allocation procedure, josaa registration steps",
         "JEE College Predictor", "/jee/college-predictor",
         "Comprehensive walkthrough of JoSAA timeline, choice locking rules, mock seat allocations, document verification, and seat acceptance fee.",
         "YES", "HIGH"),
        ("Home State Quota vs Other State Quota in NITs: Complete Eligibility and Cutoff Rules",
         "Explanation", "Educational", "home state quota vs other state quota nits",
         "nit home state eligibility, 50 percent quota in nits, hs vs os closing ranks",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Explain the 50% reservation for candidates who completed Class 12 in the state where the NIT is located, comparing HS and OS closing ranks.",
         "YES", "HIGH"),
        ("Opening Rank vs Closing Rank: What Do They Actually Mean in JoSAA?",
         "Explanation", "Educational", "opening rank vs closing rank josaa",
         "meaning of closing rank, josaa opening closing ranks explained, cutoff interpretation",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Explain that Opening Rank represents the highest-scoring candidate admitted, while Closing Rank represents the final candidate admitted to that branch.",
         "YES", "HIGH"),
        ("Difference Between Freeze, Float, and Slide in JoSAA Seat Allocation",
         "Comparison", "Educational", "freeze float slide in josaa",
         "josaa seat options explained, what is float option, when to use slide option",
         "JEE College Predictor", "/jee/college-predictor",
         "Clear functional guide on what happens when you select Freeze (accept & exit), Float (accept & upgrade anywhere), or Slide (upgrade within same institute).",
         "YES", "HIGH"),
        ("How to Use a JEE College Predictor Effectively: Avoiding Common Pitfalls",
         "Calculator Guide", "Calculator", "how to use jee college predictor",
         "predicting engineering colleges, college predictor tool studenttools, accurate college prediction",
         "JEE College Predictor", "/jee/college-predictor",
         "Guide users on filtering by category, home state, gender pool, and understanding statistical probability bands rather than taking predictions as guarantees.",
         "YES", "HIGH"),
        ("Top NITs vs New IIITs: Which One Should You Choose for Computer Science?",
         "Comparison", "Comparison", "top nits vs new iiits for cse",
         "nit vs iiit placement, iiit cse cutoff vs nit cse, choosing between nit and iiit",
         "JEE College Predictor", "/jee/college-predictor",
         "Compare infrastructure, curriculum focus (specialized IT vs comprehensive university), placement statistics, fee structures, and campus life.",
         "YES", "HIGH"),
        ("Government Funded Technical Institutes (GFTIs): Cutoffs, Fees, and Quality Review",
         "Guide", "Reference", "gfti colleges through jee main",
         "gfti list josaa, gfti cutoffs and placements, are gftis worth joining",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Overview of prominent GFTIs (PEC Chandigarh, BIT Mesra, IIEST Shibpur, JNU SE) with closing rank ranges, fee structures, and return on investment.",
         "YES", "HIGH"),
        ("Computer Science vs Information Technology in NITs: Syllabus and Cutoff Comparison",
         "Comparison", "Comparison", "cse vs it in nits",
         "difference between cse and it engineering, cse vs it cutoffs, placement difference cse it",
         "JEE College Predictor", "/jee/college-predictor",
         "Compare academic curriculum, elective overlap, career opportunities, and historical closing rank differences between CSE and IT branches.",
         "YES", "HIGH"),
        ("Artificial Intelligence and Data Science Branches in NITs: Cutoffs and Value",
         "Guide", "Educational", "ai and data science in nits cutoff",
         "ai ds engineering cutoff, artificial intelligence branch closing rank, is ai branch good in nit",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Analyze emerging specialized AI/DS branches in NITs and IIITs, evaluating curriculum structure and placement outcomes vs traditional CSE.",
         "YES", "HIGH"),
        ("Electronics and Communication Engineering (ECE) Cutoffs in Top NITs",
         "Guide", "Reference", "ece cutoff in top nits",
         "nit ece closing rank, electronics engineering cutoff josaa, safe rank for ece in nits",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Review ECE closing ranks across tier-1 NITs, semiconductor/core industry scope, and software placement eligibility.",
         "YES", "HIGH"),
        ("Electrical Engineering Cutoffs and Career Prospects Across NITs",
         "Guide", "Reference", "electrical engineering cutoff nits",
         "ee branch closing rank nit, electrical engineering admission rank, core engineering nits",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Review EE cutoffs across premier NITs, PSU eligibility through GATE, and IT recruitment crossover opportunities.",
         "YES", "MEDIUM"),
        ("Mechanical Engineering Cutoffs in Tier-1 NITs: Is It Still Worth Pursuing?",
         "Guide", "Reference", "mechanical engineering cutoff in nits",
         "nit mechanical closing rank, core mechanical placement nits, mechanical engineering ranking",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Evaluate Mechanical Engineering cutoffs in top NITs, highlighting automotive, robotics, aerospace, and analytics pathways.",
         "YES", "MEDIUM"),
        ("Civil and Chemical Engineering Cutoffs in Top NITs: High Brand vs Core Branch",
         "Guide", "Educational", "civil and chemical engineering cutoffs in top nits",
         "nit civil closing rank, chemical engineering cutoff nit, brand name vs branch dilemma",
         "JEE College Predictor", "/jee/college-predictor",
         "Navigate the classic decision: selecting lower-demand branches at elite NITs (Trichy, Surathkal) vs CSE at newer institutes.",
         "YES", "HIGH"),
        ("How to Fill JoSAA Choice List to Minimize Risk of Getting No College",
         "Guide", "Planning", "how to fill josaa choices safely",
         "josaa choice filling strategy, order of choices josaa, avoiding zero allocation josaa",
         "JEE College Predictor", "/jee/college-predictor",
         "Strategic 3-bucket framework: Dream Choices (above rank), Realistic Choices (around rank), and Safety Choices (well below rank).",
         "YES", "HIGH"),
        ("Can You Change Your Branch After First Year in an NIT?",
         "Explanation", "Educational", "branch change in nits rules",
         "internal branch sliding nit, cgpa required for branch change, has nit stopped branch change",
         "JEE College Predictor", "/jee/college-predictor",
         "Detail recent institute policies on branch change, minimum first-year CGPA criteria (typically 8.5+ or 9.0+), and recent policy updates.",
         "YES", "HIGH"),
        ("How Mock Seat Allocation in JoSAA Helps You Fine-Tune Your Choices",
         "Explanation", "How-To", "josaa mock seat allocation meaning",
         "mock round 1 2 josaa, how accurate is mock allocation, editing choices after mock round",
         "JEE College Predictor", "/jee/college-predictor",
         "Explain how mock rounds simulate candidate behavior based on initial choices, and how to use mock results to reorder preferences before choice locking.",
         "YES", "HIGH"),
        ("Dual Degree vs 4-Year B.Tech in NITs: Cutoffs and Pros & Cons",
         "Comparison", "Comparison", "dual degree vs btech in nits",
         "btech mtech integrated course nit, dual degree cutoff josaa, is dual degree worth it",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "Compare 5-year integrated B.Tech + M.Tech programs with standard 4-year B.Tech programs in terms of cutoffs, academic rigor, and recruitment.",
         "YES", "MEDIUM"),
        ("What Happens If You Miss the JoSAA Seat Acceptance Fee Deadline?",
         "Explanation", "Reference", "missed josaa seat acceptance fee deadline",
         "cancellation of josaa seat, can i enter next round after missing fee, josaa fee rules",
         "JEE College Predictor", "/jee/college-predictor",
         "Warn students about automatic cancellation of allocated seats and forfeiture of eligibility in remaining JoSAA rounds if deadlines are missed.",
         "YES", "HIGH"),
        ("Document Verification in JoSAA: Required Certificates and Common Rejection Causes",
         "Guide", "Reference", "documents required for josaa counselling",
         "josaa certificate format, obc ncl certificate date josaa, medical certificate format engineering",
         "JEE College Predictor", "/jee/college-predictor",
         "Checklist of essential documents: Class 10/12 marksheets, valid Category certificates issued after April 1, PwD disability certificates, and state domicile proofs.",
         "YES", "HIGH"),
        ("North Eastern NITs: Cutoffs, Infrastructure, and Career Prospects",
         "Guide", "Reference", "north east nits cutoffs and placements",
         "nit meghalaya agartala arunachal cutoffs, low rank nit options, are north east nits good",
         "JEE Cutoff Explorer", "/jee/cutoff",
         "In-depth look at NIT Meghalaya, Silchar, Agartala, Arunachal Pradesh, Manipur, Mizoram, Nagaland, and Sikkim with closing ranks and campus progress.",
         "YES", "MEDIUM"),
    ]

    colleges_list = [
        ("NIT Trichy", "nit trichy cutoff branch wise", "nit trichy cse closing rank, nit trichy home state cutoff", "HIGH"),
        ("NIT Surathkal", "nit surathkal cutoff ranks", "nit surathkal cse closing rank, nit surathkal admission rank", "HIGH"),
        ("NIT Warangal", "nit warangal cutoff ranks", "nit warangal cse closing rank, nit warangal cutoffs josaa", "HIGH"),
        ("NIT Rourkela", "nit rourkela cutoff branch wise", "nit rourkela cse closing rank, nit rourkela admission rank", "HIGH"),
        ("NIT Calicut", "nit calicut cutoff ranks", "nit calicut cse cutoff, nit calicut closing rank josaa", "HIGH"),
        ("VNIT Nagpur", "vnit nagpur cutoff ranks", "vnit nagpur cse cutoff, vnit nagpur closing rank", "HIGH"),
        ("MNIT Jaipur", "mnit jaipur cutoff ranks", "mnit jaipur cse cutoff, mnit jaipur closing rank", "HIGH"),
        ("MNNIT Allahabad", "mnnit allahabad cutoff ranks", "mnnit allahabad cse cutoff, mnnit closing rank josaa", "HIGH"),
        ("NIT Kurukshetra", "nit kurukshetra cutoff ranks", "nit kurukshetra cse cutoff, nit kurukshetra admission rank", "MEDIUM"),
        ("NIT Durgapur", "nit durgapur cutoff ranks", "nit durgapur cse cutoff, nit durgapur closing rank", "MEDIUM"),
        ("NIT Silchar", "nit silchar cutoff ranks", "nit silchar cse cutoff, nit silchar closing rank", "MEDIUM"),
        ("NIT Jamshedpur", "nit jamshedpur cutoff ranks", "nit jamshedpur cse cutoff, nit jamshedpur placement cutoff", "MEDIUM"),
        ("NIT Bhopal", "manit bhopal cutoff ranks", "manit bhopal cse closing rank, nit bhopal admission rank", "MEDIUM"),
        ("NIT Jalandhar", "nit jalandhar cutoff ranks", "nit jalandhar cse cutoff, nit jalandhar closing rank", "MEDIUM"),
        ("NIT Hamirpur", "nit hamirpur cutoff ranks", "nit hamirpur cse cutoff, nit hamirpur admission rank", "MEDIUM"),
        ("NIT Patna", "nit patna cutoff ranks", "nit patna cse cutoff, nit patna closing rank josaa", "MEDIUM"),
        ("NIT Raipur", "nit raipur cutoff ranks", "nit raipur cse cutoff, nit raipur admission rank", "MEDIUM"),
        ("NIT Goa", "nit goa cutoff ranks", "nit goa cse cutoff, nit goa closing rank josaa", "MEDIUM"),
        ("NIT Srinagar", "nit srinagar cutoff ranks", "nit srinagar cse cutoff, nit srinagar admission rank", "MEDIUM"),
        ("NIT Agartala", "nit agartala cutoff ranks", "nit agartala cse cutoff, nit agartala closing rank", "MEDIUM"),
        ("NIT Meghalaya", "nit meghalaya cutoff ranks", "nit meghalaya cse cutoff, nit meghalaya admission rank", "LOW"),
        ("NIT Puducherry", "nit puducherry cutoff ranks", "nit puducherry cse cutoff, nit puducherry closing rank", "LOW"),
        ("NIT Uttarakhand", "nit uttarakhand cutoff ranks", "nit uttarakhand cse cutoff, nit uttarakhand admission rank", "LOW"),
        ("NIT Andhra Pradesh", "nit andhra pradesh cutoff ranks", "nit ap cse cutoff, nit andhra closing rank", "MEDIUM"),
        ("IIIT Hyderabad", "iiit hyderabad jee main cutoff", "iiit hyderabad cse cutoff, iiit hyderabad admission through jee", "HIGH"),
        ("IIIT Bangalore", "iiit bangalore cutoff jee main", "iiit bangalore cse cutoff, iiit bangalore admission rank", "HIGH"),
        ("IIIT Allahabad", "iiit allahabad cutoff ranks", "iiit allahabad it closing rank, iiit allahabad josaa cutoff", "HIGH"),
        ("IIIT Delhi", "iiit delhi jac cutoff ranks", "iiit delhi cse cutoff, iiit delhi admission rank jee", "HIGH"),
        ("IIIT Gwalior", "iiit gwalior cutoff ranks", "iiit gwalior cse cutoff, iiit gwalior closing rank", "MEDIUM"),
        ("IIIT Jabalpur", "iiit jabalpur cutoff ranks", "iiit jabalpur cse cutoff, iiit jabalpur closing rank", "MEDIUM"),
        ("IIIT Kancheepuram", "iiit kancheepuram cutoff ranks", "iiit kancheepuram cse cutoff, iiit dm closing rank", "MEDIUM"),
        ("IIIT Lucknow", "iiit lucknow cutoff ranks", "iiit lucknow cse closing rank, iiit lucknow placement and cutoff", "HIGH"),
        ("IIIT Sri City", "iiit sri city cutoff ranks", "iiit sri city cse cutoff, iiit sri city admission rank", "MEDIUM"),
        ("IIIT Vadodara", "iiit vadodara cutoff ranks", "iiit vadodara cse cutoff, iiit vadodara closing rank", "MEDIUM"),
        ("IIIT Guwahati", "iiit guwahati cutoff ranks", "iiit guwahati cse cutoff, iiit guwahati admission rank", "MEDIUM"),
        ("IIIT Kota", "iiit kota cutoff ranks", "iiit kota cse cutoff, iiit kota closing rank josaa", "MEDIUM"),
        ("DTU Delhi", "dtu delhi cutoff jee main", "dtu cse cutoff jac delhi, dtu admission closing rank", "HIGH"),
        ("NSUT Delhi", "nsut delhi cutoff ranks", "nsut cse cutoff, nsut closing rank jac delhi", "HIGH"),
        ("BIT Mesra", "bit mesra cutoff jee main", "bit mesra cse closing rank, bit mesra josaa cutoff", "MEDIUM"),
        ("PEC Chandigarh", "pec chandigarh cutoff ranks", "pec chandigarh cse cutoff, pec closing rank", "MEDIUM"),
    ]
    for inst, kw, sec, prio in colleges_list:
        clg.append((
            f"{inst} Cutoff Explorer: Branch-Wise Closing Ranks and Admission Guide",
            "Guide", "Reference", kw, sec,
            "JEE Cutoff Explorer", "/jee/cutoff",
            f"Examine closing ranks, quota distributions, category cutoffs, and recent admission trends for {inst} through JoSAA and CSAB.",
            "YES", prio
        ))

    for item in clg:
        topics.append({
            "topic": item[0], "category": "JEE", "topic_cluster": "College Prediction",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 5. Exam Planning & Countdown (35 topics)
    # -------------------------------------------------------------
    ep = [
        ("How to Build a 30-Day Revision Plan Using an Exam Countdown Timer",
         "Planning Guide", "Planning", "30 day revision plan for jee main",
         "jee main countdown revision, last month strategy jee, daily study schedule jee 30 days",
         "JEE Exam Countdown", "/jee/countdown",
         "Structure a daily revision schedule dividing available hours across high-yield formulas, PYQs, mock tests, and error logs as exam day approaches.",
         "YES", "HIGH"),
        ("How Many Days Left for JEE Main Session 1? Realistic Milestone Planning",
         "Planning Guide", "Planning", "days left for jee main session 1",
         "jee main exam date countdown, countdown to session 1 jee, milestone planning jee",
         "JEE Exam Countdown", "/jee/countdown",
         "Guide students through backward planning from exam day: allocating time blocks for syllabus completion, mock marathons, and final review.",
         "SEASONAL", "HIGH"),
        ("How to Manage Stress and Burnout as the Exam Countdown Nears Zero",
         "Guide", "Informational", "exam stress management jee main",
         "handling panic before jee, exam day anxiety engineering, mental preparation jee",
         "JEE Exam Countdown", "/jee/countdown",
         "Evidence-based strategies for sleep hygiene, managing exam week anxiety, pacing mock tests, and maintaining emotional stamina.",
         "YES", "MEDIUM"),
        ("The Last 7 Days Before JEE Main: What to Study and What to Avoid",
         "Guide", "Planning", "last week preparation for jee main",
         "what to do 7 days before jee, last minute revision jee, avoiding burnout before exam",
         "JEE Exam Countdown", "/jee/countdown",
         "Specific recommendations for the final week: stopping new concepts, reviewing formula sheets, practicing exam-slot mock tests, and circadian rhythm tuning.",
         "YES", "HIGH"),
        ("How to Adjust Your Sleep Cycle for JEE Main Morning Shift (9 AM - 12 PM)",
         "Guide", "How-To", "how to adjust sleep cycle for jee main morning shift",
         "circadian rhythm exam prep, waking up early for jee, morning shift mental alertness",
         "JEE Exam Countdown", "/jee/countdown",
         "Explain the neurological impact of circadian rhythm adjustments 2-3 weeks before the exam so peak cognitive alertness coincides with the morning shift.",
         "YES", "MEDIUM"),
        ("Why Daily Countdown Tracking Boosts Consistency in Competitive Exam Preparation",
         "Explanation", "Educational", "benefits of exam countdown tracking",
         "urgency in exam prep, study momentum countdown timer, tracking days left for competitive exams",
         "JEE Exam Countdown", "/jee/countdown",
         "Explore the psychological power of visual countdown timers in breaking procrastination, instilling focused urgency, and measuring daily output.",
         "YES", "LOW"),
        ("How to Plan Full-Length Mock Tests in the Final 60 Days of JEE Preparation",
         "Planning Guide", "Planning", "how many mock tests before jee main",
         "mock test frequency last 60 days, analyzing full length tests, mock schedule countdown",
         "JEE Exam Countdown", "/jee/countdown",
         "Recommended timeline: moving from 1 mock test per week at 60 days down to alternate days at 30 days, leaving the final 5 days for consolidation.",
         "YES", "HIGH"),
        ("JEE Main Session 1 vs Session 2: How to Rebuild Momentum Between Exam Dates",
         "Planning Guide", "Planning", "strategy between jee session 1 and session 2",
         "improving score in session 2, gap between session 1 and 2, planning for april attempt",
         "JEE Exam Countdown", "/jee/countdown",
         "Tactical guide on analyzing Session 1 performance gaps, addressing weak chapters, and planning a 60-day turnaround for Session 2.",
         "YES", "HIGH"),
        ("Checklist for JEE Main Exam Day: Documents, Dress Code, and Reporting Time",
         "Guide", "Reference", "jee main exam day checklist",
         "nta dress code rules jee, admit card undertaking photo, what to carry to jee exam centre",
         "JEE Exam Countdown", "/jee/countdown",
         "Comprehensive practical checklist: printed admit card, valid original photo ID, transparent ballpoint pen, passport photographs, and permissible clothing.",
         "YES", "HIGH"),
        ("How to Calculate Total Available Study Hours Before Your JEE Exam Date",
         "How-To", "How-To", "how to calculate study hours before jee",
         "time budgeting for jee, remaining hours calculator exam, daily study planner",
         "JEE Exam Countdown", "/jee/countdown",
         "Provide a calculation framework deducting school/board exams, coaching, sleep, and rest to find net productive study hours remaining.",
         "YES", "HIGH"),
        ("Balancing Class 12 Board Exams with JEE Main Countdown: The Dual-Prep Strategy",
         "Planning Guide", "Planning", "balancing 12th boards and jee main",
         "cbse board exam vs jee preparation, managing boards and competitive exams, study timetable boards jee",
         "JEE Exam Countdown", "/jee/countdown",
         "Framework for synchronizing NCERT syllabus revision for board subjective questions while simultaneously solving multiple-choice JEE problems.",
         "YES", "HIGH"),
        ("How to Structure a 90-Day Comprehensive Syllabus Crash Plan for JEE Main",
         "Planning Guide", "Planning", "90 day study plan for jee main",
         "3 month jee main strategy, complete syllabus in 90 days, crash study routine",
         "JEE Exam Countdown", "/jee/countdown",
         "Weekly syllabus milestone breakdown distributing 90 chapters across Physics, Chemistry, and Mathematics over a 12-week block.",
         "YES", "HIGH"),
        ("15-Day Formula Revision Roadmap for Physics and Physical Chemistry",
         "Guide", "Planning", "15 day formula revision jee",
         "physics formula revision jee, chemistry formula sheet prep, quick revision before exam",
         "JEE Exam Countdown", "/jee/countdown",
         "Actionable day-by-day formula consolidation guide targeting mechanics, electrodynamics, thermodynamics, and physical chemistry calculations.",
         "YES", "HIGH"),
        ("How to Simulate Real Exam Conditions During Mock Tests at Home",
         "How-To", "How-To", "how to simulate jee exam at home",
         "mock test environment setup, no phone mock test rule, exact shift timing mock test",
         "JEE Exam Countdown", "/jee/countdown",
         "Guide to setting up an exam desk, strictly adhering to 9 AM - 12 PM or 3 PM - 6 PM slots, avoiding breaks, and using paper rough sheets.",
         "YES", "MEDIUM"),
        ("Handling Center Relocation and Travel Planning for Outstation JEE Candidates",
         "Guide", "Planning", "travel planning for jee main exam centre",
         "exam centre reporting guidelines, outstation exam travel checklist, avoiding exam day rush",
         "JEE Exam Countdown", "/jee/countdown",
         "Practical logistics advice: visiting the exam center a day in advance, traffic allowance, and morning commute buffers.",
         "YES", "LOW"),
        ("How to Overcome the Mid-Preparation Slump 45 Days Before JEE Main",
         "Guide", "Informational", "mid preparation slump jee",
         "losing motivation during jee prep, how to stay focused before exam, rebuilding study stamina",
         "JEE Exam Countdown", "/jee/countdown",
         "Psychological strategies to navigate the common dip in motivation 6 weeks prior to the exam when syllabus fatigue peaks.",
         "YES", "MEDIUM"),
        ("Designing an Error Notebook: How to Track and Eliminate Recurring Mistakes",
         "How-To", "How-To", "how to make error notebook for jee",
         "error analysis diary jee, eliminating silly mistakes, revision from mistake book",
         "JEE Exam Countdown", "/jee/countdown",
         "Step-by-step method to record silly mistakes, conceptual oversights, and forgotten formulas to review in the final 48 hours before the exam.",
         "YES", "HIGH"),
        ("How Many Hours Should You Sleep During the Final Month of JEE Preparation?",
         "Guide", "Informational", "how many hours of sleep for jee student",
         "sleep hygiene exam prep, all nighters before jee, cognitive performance and sleep",
         "JEE Exam Countdown", "/jee/countdown",
         "Scientific explanation of why 7 hours of uninterrupted sleep enhances memory consolidation and prevents disastrous calculation fog on exam day.",
         "YES", "MEDIUM"),
        ("Revision Prioritization: Weightage-Based Chapter Ranking for Last-Minute Prep",
         "Guide", "Reference", "high weightage chapters for jee main",
         "most important chapters jee physics chemistry maths, scoring topics jee main, weightage ranking",
         "JEE Exam Countdown", "/jee/countdown",
         "Comprehensive chart of historically high-yield chapters (Modern Physics, Current Electricity, Coordination Compounds, Matrices, Vectors).",
         "YES", "HIGH"),
        ("What to Eat on Exam Day: Nutrition and Hydration Tips for Peak Mental Focus",
         "Guide", "Informational", "what to eat before jee exam",
         "exam day breakfast tips, staying hydrated during exam, avoiding food coma morning shift",
         "JEE Exam Countdown", "/jee/countdown",
         "Nutritional advice for steady blood glucose release, avoiding sugar crashes, and optimal hydration during a 3-hour high-intensity exam.",
         "YES", "LOW"),
        ("Analyzing Past 5 Years JEE Main Session Dates and Timeline Patterns",
         "Explanation", "Reference", "jee main exam date trends historical",
         "nta exam schedule pattern, session 1 and 2 date gaps, historical notification timeline",
         "JEE Exam Countdown", "/jee/countdown",
         "Review of NTA's operational timelines from notification release to application correction, admit card issuance, and exam days.",
         "YES", "LOW"),
        ("How to Use Pomodoro Sessions Effectively During Intensive JEE Revision",
         "How-To", "How-To", "pomodoro technique for jee preparation",
         "study intervals for competitive exams, 50 minute study blocks, productivity techniques engineering prep",
         "JEE Exam Countdown", "/jee/countdown",
         "Adapting the standard Pomodoro into 90-minute or 180-minute blocks that train mental endurance for 3-hour continuous examination sessions.",
         "YES", "MEDIUM"),
        ("Last-Minute Inorganic Chemistry Revision: Memory Retaining Strategies",
         "Guide", "How-To", "inorganic chemistry last minute revision",
         "memorizing periodic table reactions, ncert inorganic revision method, chemistry quick marks",
         "JEE Exam Countdown", "/jee/countdown",
         "Mnemonics, daily flashcard reviews, and targeted NCERT table scanning techniques for the final 10 days.",
         "YES", "MEDIUM"),
        ("Managing Technical Glitches and Mouse/System Freezes at NTA Test Centers",
         "Guide", "How-To", "what to do if computer freezes during jee main",
         "nta lab technical issues, computer glitch exam hall, invigilator reporting procedure",
         "JEE Exam Countdown", "/jee/countdown",
         "Protocol for candidate reassurance: NTA server timers freeze automatically on client-side crashes, and no time is lost when systems are swapped.",
         "YES", "MEDIUM"),
        ("Post-Exam Decompression: What to Do Immediately After Your JEE Shift Ends",
         "Guide", "Informational", "what to do after jee exam shift",
         "avoiding immediate answer key panic, resting after jee, transitioning to session 2",
         "JEE Exam Countdown", "/jee/countdown",
         "Healthy post-exam protocols: taking a 24-hour mental break, avoiding premature panic over unofficial memory-based answer discussions, and resetting.",
         "YES", "LOW"),
        ("How to Handle Backlogs When There Are Only 60 Days Left for JEE",
         "Planning Guide", "Planning", "how to clear backlogs for jee in 60 days",
         "clearing class 11 backlogs, incomplete syllabus strategy, prioritizing high yield topics",
         "JEE Exam Countdown", "/jee/countdown",
         "Practical triage: classifying backlog chapters into 'must-do high weightage', 'formula-only', and 'skip' to maximize net marks.",
         "YES", "HIGH"),
        ("Why Taking Mock Tests in the Afternoon Shift (3 PM - 6 PM) Requires Conditioning",
         "Explanation", "How-To", "afternoon shift preparation jee main",
         "overcoming post lunch lethargy exam, 3 to 6 shift practice, alertness training",
         "JEE Exam Countdown", "/jee/countdown",
         "Combat post-lunch circadian dips by training specifically during the 3 PM to 6 PM slot without napping for 3 weeks prior to the exam.",
         "YES", "MEDIUM"),
        ("Countdown Strategy for Repeaters and Droppers: Avoiding Complacency",
         "Planning Guide", "Planning", "dropper study strategy last 3 months",
         "repeater jee preparation countdown, avoiding burnout as a dropper, mock test intensity droppers",
         "JEE Exam Countdown", "/jee/countdown",
         "Tailored roadmap for dropper candidates focusing on eliminating recurring conceptual blind spots and managing social pressure.",
         "YES", "HIGH"),
        ("How to Review Full Syllabus Mathematics in the Final 20 Days",
         "Planning Guide", "Planning", "maths revision plan last 20 days jee",
         "revising mathematics quickly, high scoring maths chapters, formula booklet maths jee",
         "JEE Exam Countdown", "/jee/countdown",
         "Focused blueprint concentrating on high-ROI mathematical areas: Coordinate Geometry formulas, Vector-3D, Matrices, and Differential Equations.",
         "YES", "MEDIUM"),
        ("Mock Test Score Stagnation: What to Change in the Final Month",
         "Guide", "Planning", "what to do if mock scores are not improving",
         "stuck at 120 marks last month, diagnosing test errors, adjusting exam strategy",
         "JEE Exam Countdown", "/jee/countdown",
         "Diagnostic checklist to determine whether stagnation stems from weak syllabus coverage, poor speed, or unchecked negative marks.",
         "YES", "HIGH"),
        ("Understanding the CBT (Computer Based Test) Interface Before Exam Day",
         "Guide", "Educational", "nta cbt interface guide",
         "jee main computer test buttons, marked for review green purple status, answering cbt questions",
         "JEE Exam Countdown", "/jee/countdown",
         "Detailed guide to NTA's question palette colors (green, red, purple, marked for review) and evaluation rules for answered vs unanswered review flags.",
         "YES", "HIGH"),
        ("How to Allocate Your 180 Minutes Across Physics, Chemistry, and Math",
         "Guide", "Planning", "time management during 3 hours jee main",
         "how much time for chemistry in jee, physics math time allocation, optimal time distribution exam",
         "JEE Exam Countdown", "/jee/countdown",
         "Standard proven benchmark: 40-45 minutes for Chemistry, 50-55 minutes for Physics, 70-80 minutes for Math, and 10 minutes buffer.",
         "YES", "HIGH"),
        ("Admit Card Discrepancies: What to Do If Photo or Signature Is Blurred",
         "Guide", "How-To", "jee main admit card photo discrepancy",
         "nta helpline admit card error, name spelling mistake admit card, reporting exam discrepancies",
         "JEE Exam Countdown", "/jee/countdown",
         "Steps to contact NTA helpline, carry supporting government photo ID cards, and get allowed into the examination hall via undertaking.",
         "YES", "MEDIUM"),
        ("Countdown Plan for Students Starting Serious Revision from Scratch at 60 Days",
         "Planning Guide", "Planning", "can i crack jee main in 2 months",
         "starting jee prep 60 days before, realistic target 2 months jee, scoring 140+ marks quickly",
         "JEE Exam Countdown", "/jee/countdown",
         "Realistic, honest appraisal: targeting a safe 95-97 percentile by mastering 50 high-yield chapters rather than attempting the entire 90-chapter syllabus.",
         "YES", "HIGH"),
        ("Mental Rehearsal and Visualization: Enhancing Exam Day Execution",
         "Guide", "Informational", "visualization techniques for exam day",
         "mental rehearsal jee, psychological preparation test taking, staying calm in exam hall",
         "JEE Exam Countdown", "/jee/countdown",
         "Techniques used by top rankers to mentally walk through logging into the computer, handling a tough first question, and maintaining emotional composure.",
         "YES", "LOW"),
    ]

    for item in ep:
        topics.append({
            "topic": item[0], "category": "JEE", "topic_cluster": "Exam Planning",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 6. Marks Calculator & Accuracy (25 topics)
    # -------------------------------------------------------------
    mc = [
        ("How to Calculate Accurate Total Score When Questions Have Multiple Correct Options",
         "Guide", "How-To", "multiple correct answer keys jee marks calculation",
         "nta answer key multiple options, scoring disputed questions, raw mark computation",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain how NTA awards +4 to any candidate who marked either of the recognized correct options, and how to input this in the Marks Calculator.",
         "YES", "MEDIUM"),
        ("How Many Numerical Questions Should You Attempt in JEE Main Section B?",
         "Guide", "Planning", "how many questions to attempt in section b jee",
         "section b strategy jee main, selecting 5 out of 10 numericals, negative marking in numericals",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Examine strategy for picking the 5 easiest numerical questions out of 10 options to safeguard marks and avoid unnecessary negative penalties.",
         "YES", "HIGH"),
        ("Step-by-Step Guide to Calculating Accuracy Rate from Your Response Sheet",
         "How-To", "How-To", "how to calculate accuracy rate in jee",
         "accuracy percentage formula exam, measuring test efficiency, evaluating mock test accuracy",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Formula: Accuracy = (Correct Answers / Total Attempted Questions) * 100. Show how tracking this metric exposes careless mistakes.",
         "YES", "HIGH"),
        ("Why Careless Calculation Errors Cost 5 Marks Instead of 1 Mark in JEE Main",
         "Explanation", "Educational", "why negative marking costs 5 marks",
         "true cost of silly mistake jee, 4 marks lost plus 1 negative, calculation error impact",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain the opportunity cost mathematics: getting a question wrong awards -1 instead of +4, creating a net 5-mark deficit relative to answering correctly.",
         "YES", "HIGH"),
        ("How to Use a Marks Calculator to Simulate 'What-If' Scoring Scenarios",
         "Calculator Guide", "Calculator", "what if score simulation jee main",
         "simulating jee marks, how accuracy changes percentile, target score calculation",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Guide students through testing alternative outcomes: what if 5 wrong guesses were left unattempted? How does that change the total score?",
         "YES", "HIGH"),
        ("Common Decimal and Rounding Off Errors in JEE Main Numerical Questions",
         "Guide", "Reference", "rounding off rules in jee main numerical questions",
         "decimal precision nta numericals, rounding up or down jee, truncated answers exam",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Review NTA instructions on rounding off numerical values to the nearest integer or specified decimal places, preventing avoidable zero-score outcomes.",
         "YES", "MEDIUM"),
        ("How to Cross-Check Unofficial Coaching Answer Keys with NTA Provisional Key",
         "How-To", "How-To", "coaching answer key vs nta answer key",
         "allen resonance key difference, disputed answers jee, verifying response sheet",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Guide on resolving discrepancies between preliminary coaching solutions and official NTA provisional answer keys before raising formal challenges.",
         "YES", "MEDIUM"),
        ("Calculating Subject-Wise Efficiency: Marks Scored per Minute Invested",
         "Formula Guide", "Educational", "marks per minute efficiency in jee",
         "exam time efficiency formula, subject return on investment jee, scoring rate analysis",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Introduce efficiency metric: Marks Scored / Minutes Spent. Demonstrate why Chemistry often yields 1.5 marks/min while Math yields 0.6 marks/min.",
         "YES", "MEDIUM"),
        ("Why Do Students Overestimate Their JEE Marks After Leaving the Exam Hall?",
         "Explanation", "Informational", "why do students overestimate jee marks",
         "memory based answer key bias, post exam optimism, calculation reality check",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain psychological confirmation bias where students remember confident answers while overlooking subtle reading traps and calculation slips.",
         "YES", "LOW"),
        ("How to Calculate Your Expected Marks When Options Are Shuffled Across Papers",
         "Guide", "How-To", "shuffled options in jee response sheet",
         "question id vs option id nta, matching response sheet with master question paper, answer key mapping",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain how NTA uses unique Question IDs and Option IDs rather than simple ABCD letters, showing how to map them without errors.",
         "YES", "HIGH"),
        ("What Is a Good Accuracy Percentage in JEE Main to Guarantee a 99 Percentile?",
         "Guide", "Educational", "good accuracy percentage for 99 percentile jee",
         "target accuracy for top rank, accuracy rate of toppers, how many wrong questions acceptable",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Demonstrate that toppers maintain 88% to 94% accuracy, typically attempting 60-68 questions with fewer than 5-7 errors overall.",
         "YES", "HIGH"),
        ("Analyzing Negative Marks in Physics: Units and Dimensions Traps",
         "Guide", "Educational", "common traps in jee physics questions",
         "si unit conversion errors, sign conventions electrostatics, avoiding negative marks physics",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Highlight recurring question traps: cm vs m, grams vs kg, degree vs radian, and sign conventions in optics and mechanics.",
         "YES", "MEDIUM"),
        ("How Chemistry Sign Conventions in Thermodynamics Cause Avoidable Penalties",
         "Guide", "Educational", "thermodynamics sign convention jee chemistry",
         "work done by system vs on system, physics vs chemistry thermodynamics signs, negative marks chemistry",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Highlight the frequent point of confusion between Chemistry (IUPAC work conventions) and Physics sign conventions.",
         "YES", "MEDIUM"),
        ("How to Recalculate Your Score After Final Answer Key Revisions",
         "How-To", "How-To", "recalculating marks after final answer key jee",
         "revised final answer key nta, score change after challenge, final marks before rank",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Walk through adjusting score calculations when NTA accepts challenges, drops questions, or modifies correct options in the final answer key.",
         "YES", "HIGH"),
        ("The Math of Risk-Taking: When Does Guessing Yield Positive Net Returns in JEE?",
         "Formula Guide", "Educational", "mathematics of guessing in competitive exams",
         "expected value formula guessing, probability of multiple choice questions, blind vs informed guessing",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Rigorous mathematical analysis of expected value E = P(correct) * 4 - P(wrong) * 1. Show when expected value is positive.",
         "YES", "HIGH"),
        ("How to Audit Your Answer Sheet for OMR/Click Registration Errors",
         "Guide", "How-To", "verifying recorded response in nta response sheet",
         "cbt click saving errors, save and next button verification, marked for review scoring",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain how NTA captures recorded responses, confirming that 'Save & Next' ensures answers are logged for evaluation.",
         "YES", "MEDIUM"),
        ("Comparing Raw Marks Calculation in JEE Main vs NEET Examination",
         "Comparison", "Comparison", "jee main vs neet marking scheme comparison",
         "neet 720 marks vs jee 300 marks, negative marking comparison medical engineering, scoring difficulty",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Compare maximum marks (300 vs 720), question volume, time per question (2.4 min vs 1 min), and accuracy benchmarks.",
         "YES", "LOW"),
        ("How Many Marks Can You Gain by Eliminating Calculation Slip Errors Alone?",
         "Explanation", "Educational", "how to eliminate calculation mistakes in jee",
         "rough sheet organization, margin calculation method, gaining 20 marks in jee",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Demonstrate that clean, numbered rough work prevents 3-5 calculation slips, immediately yielding a net 15-25 mark improvement.",
         "YES", "HIGH"),
        ("Evaluating Question Difficulty Level in Mock Tests: Easy, Moderate, Tough Tally",
         "How-To", "How-To", "categorizing questions by difficulty in test analysis",
         "post test difficulty matrix, easy question accuracy, identifying silly mistakes in easy questions",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Provide a spreadsheet template to classify all 75 questions by difficulty and audit whether any 'Easy' questions were missed.",
         "YES", "MEDIUM"),
        ("Why Do Negative Marks Spike in the Last 20 Minutes of the Exam?",
         "Explanation", "Informational", "panic guessing last 20 minutes jee",
         "time pressure errors exam, avoiding desperate attempts, maintaining discipline under clock",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Analyze the psychology of panic when the countdown timer turns red, prompting desperate unverified guesses that erode hard-earned marks.",
         "YES", "MEDIUM"),
        ("How to Set Up a Target Marks Scorecard for JEE Main Session 2",
         "Planning Guide", "Planning", "setting target score for jee session 2",
         "session 2 marks goal, realistic score improvement, target scorecard template",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Break down target score into subject-level milestones (e.g. Chemistry 75, Physics 70, Math 45 = 190 total marks).",
         "YES", "HIGH"),
        ("Understanding the Impact of Equal Scores on Rank Distribution",
         "Explanation", "Reference", "marks density around average scores jee",
         "score congestion 120 marks, how many students on same marks, rank variance per mark",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Show how score density peaks between 100 and 130 marks, where a single 1-mark swing can alter ranking by 3,000 to 5,000 positions.",
         "YES", "HIGH"),
        ("How to Use Past Years' Answer Keys to Practice Scoring Drill Sessions",
         "How-To", "How-To", "practicing with official nta pyqs and answer keys",
         "pyq paper solving scoring, timing past papers, authentic score evaluation",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain how to take past papers as timed tests and use authentic NTA keys to calculate reliable baseline scores.",
         "YES", "MEDIUM"),
        ("The Psychological Benefit of Knowing Your Exact Raw Score Quickly",
         "Explanation", "Informational", "benefits of early marks calculation after jee",
         "planning after exam key release, reducing result anxiety, early counselling preparation",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Explain how immediate, accurate score tallying grounds expectations, reduces anxiety, and enables quick decision-making for JEE Advanced or Session 2.",
         "YES", "LOW"),
        ("Summary Guide: Essential Formulas for JEE Main Marks, Accuracy, and Negative Penalties",
         "Formula Guide", "Reference", "jee scoring formulas summary",
         "all scoring formulas competitive exams, net marks formula, accuracy rate calculation",
         "JEE Marks Calculator", "/jee/marks-calculator",
         "Consolidated reference table of all core scoring formulas: Raw Score, Accuracy Rate, Error Rate, Expected Value, and Opportunity Cost.",
         "YES", "HIGH"),
    ]

    for item in mc:
        topics.append({
            "topic": item[0], "category": "JEE", "topic_cluster": "Marks Calculator",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    return topics

if __name__ == "__main__":
    t = get_jee_topics()
    print(f"Total JEE topics generated: {len(t)}")
