"""
General Calculators Topics Generator for StudentTools.cyou
Target: 180 distinct, high-quality, practical topics across:
1. Age & Date of Birth (25)
2. BMI & Body Mass Index (25)
3. Unit Conversion (45)
4. Date & Calendar Calculations (20)
5. Discount & Savings (20)
6. Profit and Loss (15)
7. Ratio & Proportion (15)
8. Fractions & Operations (15)
"""

def get_general_topics():
    topics = []

    # -------------------------------------------------------------
    # 1. Age & Date of Birth (25 topics)
    # Related Tool: Age Calculator (/calculators/age)
    # -------------------------------------------------------------
    age_data = [
        ("How Chronological Age Is Calculated: Step-by-Step Years, Months, and Days Math",
         "Formula Guide", "How-To", "how chronological age is calculated",
         "chronological age formula, calculate exact age in years months days, dob to current age math",
         "Age Calculator", "/calculators/age",
         "Explain day, month, and year borrowing rules: borrowing 30 or 31 days depending on previous month length, and borrowing 12 months when current month is less than birth month.",
         "YES", "HIGH"),
        ("How to Calculate Exact Age as of a Specific Cutoff Date for Government Exams (UPSC, SSC, IBPS)",
         "Guide", "How-To", "how to calculate age on cutoff date for exam",
         "upsc age eligibility calculation, ssc age calculator cutoff date, determining age on 1st august",
         "Age Calculator", "/calculators/age",
         "Guide aspirants on determining eligibility as of official cutoff dates (e.g., August 1st for UPSC Civil Services), accounting for leap years and age relaxation rules.",
         "YES", "HIGH"),
        ("How Leap Years Affect Exact Age and Total Days Lived Calculations",
         "Explanation", "Educational", "how leap years affect age calculation",
         "leap day birthday age calculation, 365 vs 366 days age math, leap year born age",
         "Age Calculator", "/calculators/age",
         "Explain the Gregorian leap year rule (divisible by 4, except century years unless divisible by 400), and how February 29 birthdays are evaluated legally and chronologically.",
         "YES", "MEDIUM"),
        ("How to Calculate Total Days, Hours, and Minutes You Have Lived",
         "How-To", "How-To", "how many days have i lived",
         "calculate total days lived, convert age into hours and minutes, date of birth to total days",
         "Age Calculator", "/calculators/age",
         "Provide mathematical conversion steps: multiplying complete years by 365.25, adding elapsed days, and multiplying by 24 for hours and 1,440 for minutes.",
         "YES", "HIGH"),
        ("Calculating Next Birthday Countdown: Exact Days and Day of the Week",
         "How-To", "How-To", "how to calculate days until next birthday",
         "next birthday countdown formula, find what day of week was born, birthday countdown math",
         "Age Calculator", "/calculators/age",
         "Explain Zeller's congruence algorithm to find the day of the week you were born, and forward-date difference math to compute days remaining until your next birthday.",
         "YES", "HIGH"),
        ("Age Relaxation Rules in Indian Competitive Exams: SC, ST, OBC, EWS, and PwD Slabs",
         "Guide", "Reference", "age relaxation for competitive exams in india",
         "obc 3 years age relaxation, sc st 5 years age limit, government job upper age limit relaxation",
         "Age Calculator", "/calculators/age",
         "Detail statutory age extensions: +3 years for OBC-NCL, +5 years for SC/ST, +10 years for PwD, and how to verify if your exact birthdate falls within relaxed windows.",
         "YES", "HIGH"),
        ("How School Admission Minimum Age Criteria Works Under National Education Policy (NEP 2020)",
         "Guide", "Reference", "minimum age for class 1 admission nep 2020",
         "6 years age rule for class 1, cbse school admission age calculation, lkg ukg age criteria",
         "Age Calculator", "/calculators/age",
         "Explain the mandatory 6-year minimum age rule for Class 1 as of March 31 or June 1, helping parents calculate exact nursery and primary school admission eligibility.",
         "YES", "HIGH"),
        ("Why Subtracting Birth Year from Current Year Gives an Inaccurate Age Most of the Year",
         "Explanation", "Educational", "why current year minus birth year is inaccurate",
         "common age calculation mistake, accurate age vs simple subtraction, birthday not yet reached",
         "Age Calculator", "/calculators/age",
         "Explain birthday logic: if your birthday hasn't occurred yet in the current calendar year, simple year subtraction overstates your true chronological age by 1 year.",
         "YES", "HIGH"),
        ("How Half-Birthday (6-Month Milestone) Is Calculated Across Different Month Lengths",
         "Formula Guide", "How-To", "how to calculate half birthday date",
         "exact half birthday calculation, 6 months from birth date, half birthday math",
         "Age Calculator", "/calculators/age",
         "Detail day-shifting math: adding 6 months and adjusting for months with 28, 30, or 31 days (e.g. August 31 half-birthday landing in late February).",
         "YES", "LOW"),
        ("How Chronological Age Differs from Biological and Gestational Age in Pediatrics",
         "Comparison", "Educational", "chronological vs gestational age",
         "corrected age for premature babies formula, biological vs chronological age, pediatric age calculation",
         "Age Calculator", "/calculators/age",
         "Explain corrected age formulas for premature infants: Corrected Age = Chronological Age - Weeks of Prematurity, tracking developmental milestones accurately.",
         "YES", "MEDIUM"),
        ("Age Calculation for Driving License in India: The 16 vs 18 Years Rule",
         "Guide", "Reference", "minimum age for driving license in india",
         "16 years gearless scooter license, 18 years commercial license age, rto age eligibility calculation",
         "Age Calculator", "/calculators/age",
         "Explain Motor Vehicles Act rules: 16 years for gearless 50cc scooters, 18 years for private cars/bikes, and 20 years for commercial transport vehicles.",
         "YES", "HIGH"),
        ("How Voting Age Eligibility Is Calculated for Electoral Roll Registration in India",
         "Guide", "Reference", "voting age eligibility cutoff date india",
         "eci 18 years qualifying dates, election commission age cutoff, voter id age calculation",
         "Age Calculator", "/calculators/age",
         "Detail Election Commission of India rules: 4 qualifying dates per year (January 1, April 1, July 1, October 1) to enroll upon turning 18.",
         "YES", "HIGH"),
        ("Calculating Age for Senior Citizen Concessions and Bank FD Schemes (60 vs 80 Years)",
         "Guide", "Reference", "age criteria for senior citizen in india",
         "60 years senior citizen vs 80 super senior, railway concession age rule, senior citizen status cutoff",
         "Age Calculator", "/calculators/age",
         "Define Senior Citizen (age 60+) and Super Senior Citizen (age 80+) under Income Tax Section 194A/80TTB, and calculating exact qualifying dates.",
         "YES", "HIGH"),
        ("How to Calculate Age in Excel and Google Sheets: DATEDIF Function Guide",
         "How-To", "How-To", "datedif function for age calculation excel",
         "excel age formula datedif y m d, calculate age in google sheets, datedif syntax",
         "Age Calculator", "/calculators/age",
         "Provide exact spreadsheet syntax: =DATEDIF(DOB, TODAY(), 'Y') & ' Years, ' & DATEDIF(DOB, TODAY(), 'YM') & ' Months', explaining unit parameters.",
         "YES", "HIGH"),
        ("Age Gap in Relationships: How to Calculate Exact Age Difference Between Two People",
         "How-To", "How-To", "how to calculate age gap between two people",
         "age difference calculator formula, exact age gap in years and months, comparing two dates of birth",
         "Age Calculator", "/calculators/age",
         "Step-by-step subtraction of the earlier birthdate from the later birthdate, resolving borrow-overs to yield exact age gap down to days.",
         "YES", "HIGH"),
        ("Calculating Retirement Date: How Government and Corporate Superannuation Dates Are Set",
         "Guide", "Reference", "superannuation age calculation formula",
         "retirement date last day of month rule, 58 vs 60 years retirement date, central government superannuation rules",
         "Age Calculator", "/calculators/age",
         "Explain standard Indian service rules: retirement occurs on the final afternoon of the month in which the employee attains age 60 (or preceding day if born on 1st).",
         "YES", "HIGH"),
        ("How Insurance Companies Calculate 'Age Nearest Birthday' for Life Insurance Premiums",
         "Explanation", "Reference", "age nearest birthday meaning life insurance",
         "insurance age calculation, age last birthday vs age next birthday, lic policy age calculation",
         "Age Calculator", "/calculators/age",
         "Explain underwriting convention: if your birthday is within 6 months, actuaries round up to your next age, increasing term insurance premium quotes.",
         "YES", "HIGH"),
        ("Calculating Exact Age on Marriage Registration Date: Legal Age Thresholds in India",
         "Guide", "Reference", "legal marriage age in india calculation",
         "minimum marriage age 21 for male 18 for female, marriage registration age proof, legal age calculation",
         "Age Calculator", "/calculators/age",
         "Detail statutory marriage age laws under the Hindu Marriage Act and Special Marriage Act, and verifying birth certificates for registration.",
         "YES", "MEDIUM"),
        ("How Ancient Civilizations Counted Age: East Asian Age (Nominal Age) vs Western Age",
         "Comparison", "Educational", "east asian age vs western age",
         "korean age system explained, nominal age calculation, why east asian age is 1 year older",
         "Age Calculator", "/calculators/age",
         "Explain traditional systems where individuals are considered 1 year old at birth and gain a year on New Year's Day, and South Korea's recent transition to international age.",
         "YES", "LOW"),
        ("Calculating Time Saved or Lost Across Different Time Zones for Babies Born on Flight",
         "Explanation", "Informational", "date of birth baby born on international flight",
         "birth certificate international waters, timezone impact on birthdate, legal age birth on airplane",
         "Age Calculator", "/calculators/age",
         "Explore legal and astronomical nuances: UTC recording vs origin/destination time zone, and how crossing the International Date Line affects birthday records.",
         "YES", "LOW"),
        ("How to Calculate Dog Years and Cat Years to Equivalent Human Age",
         "Formula Guide", "Educational", "how to calculate dog years to human years",
         "cat age in human years formula, 7 year dog rule myth, realistic pet age conversion",
         "Age Calculator", "/calculators/age",
         "Dispel the flat 7-to-1 myth: first year of a dog equals ~15 human years, second year equals ~9 human years, and subsequent years equal ~4-5 years based on breed size.",
         "YES", "MEDIUM"),
        ("Can You Accurately Calculate Age Using Unix Epoch Timestamps?",
         "Formula Guide", "How-To", "convert unix timestamp to age",
         "epoch time difference age calculation, milliseconds to years formula, timestamp age math",
         "Age Calculator", "/calculators/age",
         "Demonstrate programming logic: subtracting birth timestamp from current timestamp and converting elapsed seconds while handling leap second edge cases.",
         "YES", "LOW"),
        ("Calculating Age for Minor Bank Accounts and PPF for Minors (Under 18 Rules)",
         "Guide", "Reference", "minor bank account age limit india",
         "ppf account for minor maturity, operational bank account age 10 years, guardian minor account rules",
         "Age Calculator", "/calculators/age",
         "Explain RBI norms: minors above 10 can independently operate savings accounts, and converting minor accounts to major status upon turning 18.",
         "YES", "MEDIUM"),
        ("How Judicial Courts Verify Age in Dispute Cases: Ossification Test vs Birth Certificate",
         "Guide", "Reference", "ossification test for age determination",
         "medical age estimation bones x ray, bone age test accuracy margin, juvenility plea age proof",
         "Age Calculator", "/calculators/age",
         "Explain forensic bone age determination via X-ray fusion of epiphyseal plates (+/- 2 years error margin) and priority of municipal birth records under JJ Act.",
         "YES", "LOW"),
        ("Summary Guide: Key Formulas and Calendar Rules for Chronological Age Calculations",
         "Formula Guide", "Reference", "chronological age formulas summary",
         "all age formulas cheat sheet, borrow over calendar math, age calculation reference guide",
         "Age Calculator", "/calculators/age",
         "Consolidated reference sheet detailing day/month borrowing rules, leap year logic, Zeller's congruence, and official examination cutoff algorithms.",
         "YES", "HIGH"),
    ]

    for item in age_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "Age",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 2. BMI & Body Mass Index (25 topics)
    # Related Tool: BMI Calculator (/calculators/bmi)
    # -------------------------------------------------------------
    bmi_data = [
        ("How Body Mass Index (BMI) Is Calculated: Metric and Imperial Mathematical Formulas",
         "Formula Guide", "How-To", "how bmi is calculated formula",
         "bmi formula metric imperial, body mass index calculation formula, kg m2 bmi formula",
         "BMI Calculator", "/calculators/bmi",
         "Derive the Quetelet formula: BMI = weight (kg) / [height (m)]^2. Provide the imperial equivalent: [weight (lbs) * 703] / [height (inches)]^2 with worked examples.",
         "YES", "HIGH"),
        ("WHO BMI Categories vs Asian Indian BMI Cutoffs: Why Indians Need Lower Thresholds",
         "Comparison", "Educational", "asian indian bmi cutoffs vs who",
         "why bmi cutoff is lower for indians, normal bmi for indians 18.5 to 22.9, thin fat phenotype india",
         "BMI Calculator", "/calculators/bmi",
         "Explain ICMR and WHO guidelines for South Asians: Overweight starts at 23.0 (vs 25.0 globally) and Obese starts at 25.0 (vs 30.0 globally) due to higher visceral fat ratios.",
         "YES", "HIGH"),
        ("BMI Limitations: Why BMI Cannot Distinguish Between Muscle Mass and Body Fat",
         "Explanation", "Educational", "limitations of bmi body mass index",
         "why bmi is flawed for athletes, muscle weight vs fat weight bmi, is bmi accurate",
         "BMI Calculator", "/calculators/bmi",
         "Explain why bodybuilders and athletes register as 'obese' on BMI charts because the formula accounts only for total weight, neglecting body composition.",
         "YES", "HIGH"),
        ("How to Calculate Your Ideal Body Weight Range from Your Height",
         "Formula Guide", "How-To", "how to calculate ideal weight from height",
         "ideal body weight formula, healthy weight range for height, devine formula ideal weight",
         "BMI Calculator", "/calculators/bmi",
         "Invert the BMI equation: Minimum Healthy Weight = 18.5 * (Height in m)^2, and Maximum Healthy Weight = 22.9 * (Height in m)^2 (Asian cutoff).",
         "YES", "HIGH"),
        ("Waist-to-Height Ratio (WHtR) vs BMI: The 0.5 Benchmark for Cardiovascular Health",
         "Comparison", "Educational", "waist to height ratio vs bmi",
         "whtr calculation formula, keep waist to half your height, abdominal obesity measurement",
         "BMI Calculator", "/calculators/bmi",
         "Introduce WHtR: Waist Circumference / Height. Explain why keeping waist under half your height (ratio < 0.5) is a superior predictor of metabolic health than BMI alone.",
         "YES", "HIGH"),
        ("How Many Kilograms Do You Need to Lose to Move from Overweight to Normal BMI?",
         "How-To", "Planning", "how many kg to lose to reach normal bmi",
         "weight loss target for healthy bmi, calculating excess weight, target weight formula",
         "BMI Calculator", "/calculators/bmi",
         "Formula: Excess Weight = Current Weight - [Target Upper BMI * (Height in m)^2]. Provide worked examples for individuals at 5'6\", 5'9\", and 6'0\".",
         "YES", "HIGH"),
        ("Child and Teen BMI: Why Percentile Charts Are Used Instead of Fixed Cutoffs",
         "Guide", "Reference", "bmi for children and teens percentile",
         "pediatric bmi chart cdc, child bmi calculation formula, age and gender specific bmi",
         "BMI Calculator", "/calculators/bmi",
         "Explain CDC and IAP growth charts: why children's body composition changes rapidly during puberty, requiring age-and-gender percentiles (5th to 85th percentile = healthy).",
         "YES", "HIGH"),
        ("What Does a BMI Under 18.5 Mean? Health Risks and Weight-Gain Calculations",
         "Guide", "Informational", "underweight bmi risks and calculation",
         "bmi below 18.5 meaning, how to calculate weight needed to reach normal bmi, underweight health consequences",
         "BMI Calculator", "/calculators/bmi",
         "Discuss nutritional deficiencies, bone density loss, immune suppression, and calculating the minimum caloric surplus needed to safely gain weight.",
         "YES", "HIGH"),
        ("How Severe Obesity (Class 1, 2, and 3) Is Categorized in Medical Screening",
         "Guide", "Reference", "bmi obesity class 1 2 3 thresholds",
         "morbid obesity bmi cutoff, severe obesity definition, bariatric surgery bmi criteria india",
         "BMI Calculator", "/calculators/bmi",
         "Detail clinical classifications: Class 1 (BMI 30-34.9), Class 2 (35-39.9), Class 3 / Morbid (40+), and Indian bariatric surgical criteria (BMI 35+ or 32+ with comorbidities).",
         "YES", "HIGH"),
        ("Basal Metabolic Rate (BMR) vs BMI: Understanding Daily Caloric Burn",
         "Comparison", "Educational", "bmr vs bmi difference",
         "how bmr is calculated harris benedict, calories burned at rest, difference between bmi and bmr",
         "BMI Calculator", "/calculators/bmi",
         "Contrast BMI (static screening ratio) with BMR (dynamic daily baseline calorie expenditure via Mifflin-St Jeor equation), showing how to calculate caloric deficits.",
         "YES", "HIGH"),
        ("How Pregnancy Affects BMI Calculations: Pre-Pregnancy BMI vs Gestational Weight Gain",
         "Guide", "Reference", "bmi calculation during pregnancy",
         "recommended weight gain pregnancy bmi, pre pregnancy bmi categories, gestational weight gain guidelines",
         "BMI Calculator", "/calculators/bmi",
         "Explain why standard BMI is invalid during pregnancy, and review IOM guidelines for recommended gestational weight gain based on pre-pregnancy BMI.",
         "YES", "HIGH"),
        ("Height Shrinkage with Age: How Osteoporosis Alters Senior Citizen BMI Calculations",
         "Explanation", "Educational", "how height loss affects bmi in elderly",
         "age related height shrinkage, osteoporosis and bmi distortion, senior citizen body mass index",
         "BMI Calculator", "/calculators/bmi",
         "Explain how spinal disc compression reduces height by 1-3 inches in older age, artificially inflating calculated BMI without any increase in body fat.",
         "YES", "MEDIUM"),
        ("How to Accurately Measure Height and Weight at Home for Precise BMI Results",
         "Guide", "How-To", "how to measure height and weight accurately at home",
         "stadiometer height measurement technique, morning weighing rules, accurate bmi input",
         "BMI Calculator", "/calculators/bmi",
         "Best practices: measuring barefoot against a flat wall with heels and shoulders touching, and weighing first thing in the morning after voiding.",
         "YES", "MEDIUM"),
        ("The 'Skinny Fat' Syndrome: Normal BMI with High Visceral Body Fat",
         "Explanation", "Educational", "skinny fat phenomenon normal bmi",
         "normal weight obesity metabolic risks, high visceral fat low muscle mass, skinny fat bmi paradox",
         "BMI Calculator", "/calculators/bmi",
         "Explain Normal Weight Obesity (NWO): individuals with a 'healthy' BMI (e.g. 21.5) who have dangerously high triglycerides, fatty liver, and low muscle tone.",
         "YES", "HIGH"),
        ("How to Calculate Body Fat Percentage from BMI and Age: Deurenberg Formula",
         "Formula Guide", "How-To", "calculate body fat percentage from bmi formula",
         "deurenberg body fat formula, estimating body fat from bmi, adult body fat calculation",
         "BMI Calculator", "/calculators/bmi",
         "Formula: Adult Body Fat % = (1.20 * BMI) + (0.23 * Age) - (10.8 * Gender) - 5.4. Show worked examples comparing male and female estimations.",
         "YES", "HIGH"),
        ("BMI Requirements for Military, Police, and Pilot Recruitment in India",
         "Guide", "Reference", "bmi criteria for nda cds defence exams",
         "army navy air force bmi medical standards, police sub inspector bmi limit, pilot medical examination bmi",
         "BMI Calculator", "/calculators/bmi",
         "Detail strict defence standards (typically BMI 18 to 25 or specialized height-weight correlation charts), and temporary rejection policies for overweight candidates.",
         "YES", "HIGH"),
        ("How Water Retention and Sodium Intake Temporarily Distort Daily BMI",
         "Explanation", "Informational", "water weight fluctuation and bmi",
         "daily weight fluctuations 2 kg, sodium bloating scale weight, when to weigh yourself",
         "BMI Calculator", "/calculators/bmi",
         "Explain biological fluid shifts: how high-sodium meals, carb loading, or intense workouts cause 1-2 kg of glycogen water retention, skewing day-to-day BMI readings.",
         "YES", "MEDIUM"),
        ("The Quetelet Index: The 19th-Century Mathematical History Behind BMI",
         "Explanation", "Educational", "history of body mass index quetelet",
         "who invented bmi adolphe quetelet, why height is squared in bmi, origins of body mass index",
         "BMI Calculator", "/calculators/bmi",
         "Explore Belgian mathematician Adolphe Quetelet's 1832 population statistics work, explaining why squaring height approximates volume-to-surface scaling.",
         "YES", "LOW"),
        ("Trikona / New BMI Formula: How Nick Trefethen Fixed the Short vs Tall Person Bias",
         "Comparison", "Educational", "oxford new bmi formula vs standard",
         "nick trefethen new bmi formula, height 2.5 power bmi, why standard bmi hates tall people",
         "BMI Calculator", "/calculators/bmi",
         "Explain Oxford mathematician Nick Trefethen's alternative formula: New BMI = 1.3 * Weight / Height^2.5, which eliminates distortion for very short and tall individuals.",
         "YES", "HIGH"),
        ("How Health Insurance Companies Use BMI to Surcharge or Reject Policy Applications",
         "Guide", "Reference", "health insurance premium loading high bmi",
         "insurance medical checkup bmi limit, bmi above 30 health insurance premium, underwriting bmi guidelines",
         "BMI Calculator", "/calculators/bmi",
         "Explain underwriting guidelines: BMIs above 30 or 32 often attract 10-30% premium loading or mandatory pre-policy medical tests for diabetes and hypertension.",
         "YES", "HIGH"),
        ("Calculating Healthy Weight Gain for Muscle Hypertrophy Without Spiking BMI Unhealthily",
         "Guide", "Planning", "clean bulking weight gain rate",
         "healthy weight gain per month, muscle gain without fat bmi, caloric surplus calculation bulking",
         "BMI Calculator", "/calculators/bmi",
         "Provide a safe physiological rate: 0.5 to 1.0 kg per month of lean tissue via a controlled 300-500 kcal surplus, preventing rapid accumulation of visceral fat.",
         "YES", "MEDIUM"),
        ("Ethnic Variations in BMI: African, European, Hispanic, and Asian Differences",
         "Comparison", "Educational", "ethnic differences in bmi cutoffs",
         "body composition across ethnicities, why one bmi cutoff does not fit all, global health standards",
         "BMI Calculator", "/calculators/bmi",
         "Compare skeletal density, muscularity, and visceral adiposity across global populations, justifying customized public health screening thresholds.",
         "YES", "MEDIUM"),
        ("How Many Calories Does 1 BMI Point Represent in Pure Body Weight?",
         "Formula Guide", "Educational", "how many calories to drop one bmi point",
         "caloric equivalent of 1 bmi point, 7700 calories per kg fat, weight loss calorie math",
         "BMI Calculator", "/calculators/bmi",
         "Calculate: For an average 1.7m adult, 1 BMI unit = 2.89 kg = ~22,250 kcal of body fat deficit (at 7,700 kcal/kg), translating to ~44 days at a 500 kcal deficit.",
         "YES", "HIGH"),
        ("Can You Have an Overweight BMI and Excellent Cardiovascular Fitness?",
         "Explanation", "Informational", "fit but fat concept bmi",
         "cardiorespiratory fitness vs bmi mortality, vo2 max vs body weight, metabolic health in overweight",
         "BMI Calculator", "/calculators/bmi",
         "Review medical literature on cardiorespiratory fitness (VO2 max) mitigating cardiovascular disease risk even among individuals categorized as overweight.",
         "YES", "MEDIUM"),
        ("Summary Guide: Essential BMI Formulas, WHO vs Asian Cutoffs, and Health Metrics",
         "Formula Guide", "Reference", "bmi formulas and classification summary",
         "all bmi formulas cheat sheet, metric imperial bmi reference, healthy weight range summary",
         "BMI Calculator", "/calculators/bmi",
         "Consolidated reference sheet detailing metric and imperial formulas, WHO global categories, Asian Indian modified cutoffs, and ideal body weight equations.",
         "YES", "HIGH"),
    ]

    for item in bmi_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "BMI",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 3. Unit Conversion (45 topics)
    # Related Tool: Unit Converter (/calculators/unit-converter)
    # -------------------------------------------------------------
    unit_data = [
        ("Length Conversion Master Guide: Meters, Feet, Inches, Kilometers, and Miles Explained",
         "Formula Guide", "Reference", "length conversion formula",
         "meters to feet conversion, km to miles formula, inches to centimeters calculation, unit conversion length",
         "Unit Converter", "/calculators/unit-converter",
         "Complete conversion matrix: 1 meter = 3.28084 feet, 1 inch = 2.54 cm, 1 mile = 1.60934 km. Show step-by-step unit cancellation methods.",
         "YES", "HIGH"),
        ("Temperature Conversion Formulas: Celsius, Fahrenheit, and Kelvin Step-by-Step",
         "Formula Guide", "How-To", "temperature conversion formula celsius fahrenheit kelvin",
         "celsius to fahrenheit formula, fahrenheit to celsius calculation, kelvin conversion formula",
         "Unit Converter", "/calculators/unit-converter",
         "Provide exact algebraic formulas: F = (C * 9/5) + 32, C = (F - 32) * 5/9, K = C + 273.15. Explain why -40 degrees is the exact same temperature in C and F.",
         "YES", "HIGH"),
        ("Land Area Measurement Units in India: Square Feet, Acres, Hectares, Bigha, and Guntha",
         "Guide", "Reference", "indian land measurement units conversion",
         "sq ft to acre conversion, bigha to sq ft in different states, guntha to sq ft calculation",
         "Unit Converter", "/calculators/unit-converter",
         "Comprehensive state-wise guide: 1 Acre = 43,560 sq ft, 1 Hectare = 2.471 Acres, 1 Guntha = 1,089 sq ft, and regional variations of Bigha across UP, Bihar, and Rajasthan.",
         "YES", "HIGH"),
        ("Mass and Weight Conversion: Kilograms, Pounds, Ounces, Grams, and Metric Tons",
         "Formula Guide", "Reference", "kg to lbs conversion formula",
         "kilograms to pounds calculation, grams to ounces formula, metric ton to kg conversion",
         "Unit Converter", "/calculators/unit-converter",
         "Exact conversion factors: 1 kg = 2.20462 lbs, 1 pound = 453.592 grams, 1 ounce = 28.3495 grams, 1 metric ton = 1,000 kg. Provide practical kitchen and gym examples.",
         "YES", "HIGH"),
        ("Speed Conversion: Kilometers per Hour (km/h) to Meters per Second (m/s) and Miles per Hour (mph)",
         "Formula Guide", "How-To", "kmph to mps conversion formula",
         "multiply by 5 18 conversion, km h to m s shortcut, speed unit conversion formula",
         "Unit Converter", "/calculators/unit-converter",
         "Explain the famous physics shortcut: multiply by 5/18 to convert km/h to m/s, and multiply by 18/5 for the reverse. Derive from (1000 m / 3600 s).",
         "YES", "HIGH"),
        ("Digital Storage Units: Megabytes (MB), Gigabytes (GB), Terabytes (TB), and Mebibytes (MiB)",
         "Explanation", "Educational", "difference between gb and gib storage",
         "1000 vs 1024 bytes, why is a 1tb hard drive only 931gb, decimal vs binary storage units",
         "Unit Converter", "/calculators/unit-converter",
         "Expose why formatted hard drives look smaller in Windows: storage manufacturers use decimal (1 GB = 10^9 bytes), while operating systems use binary Gibibytes (1 GiB = 2^30 bytes).",
         "YES", "HIGH"),
        ("Volume and Capacity Conversion: Liters, Milliliters, Gallons, Cubic Meters, and Fluid Ounces",
         "Formula Guide", "Reference", "liters to gallons conversion formula",
         "us gallon vs imperial gallon, cubic meters to liters calculation, ml to fluid ounces",
         "Unit Converter", "/calculators/unit-converter",
         "Compare US liquid gallon (3.785 L) vs UK imperial gallon (4.546 L), and formulas for 1 cubic meter = 1,000 Liters.",
         "YES", "HIGH"),
        ("Pressure Units Conversion: Pascals (Pa), Bar, PSI, Atmospheres (atm), and mmHg",
         "Formula Guide", "Reference", "pressure conversion formula bar psi pascal",
         "bar to psi tire pressure conversion, 1 atm in pascals, mmhg to bar calculation",
         "Unit Converter", "/calculators/unit-converter",
         "Provide conversion matrix for tire pressure and laboratory science: 1 bar = 14.5038 PSI = 100,000 Pa, 1 atm = 101,325 Pa = 760 mmHg.",
         "YES", "HIGH"),
        ("Power and Energy Units: Watts, Kilowatts (kW), Horsepower (HP), Joules, and Calories",
         "Formula Guide", "Reference", "kw to hp conversion formula",
         "horsepower to kilowatts conversion, electrical units to kwh calculation, joules to calories",
         "Unit Converter", "/calculators/unit-converter",
         "Conversion rules: 1 HP (metric) = 735.5 W, 1 HP (mechanical) = 745.7 W, 1 kWh (electricity unit) = 3.6 * 10^6 Joules, 1 Calorie = 4.184 Joules.",
         "YES", "HIGH"),
        ("How to Convert Fuel Economy: Kilometers per Liter (km/l) vs Miles per Gallon (mpg)",
         "Formula Guide", "How-To", "kmpl to mpg conversion formula",
         "convert km per liter to miles per gallon, l 100km to kmpl, vehicle mileage conversion",
         "Unit Converter", "/calculators/unit-converter",
         "Provide conversion formula: 1 km/L = 2.352 US mpg = 2.825 UK mpg. Explain European L/100km inverse consumption math: L/100km = 100 / (km/L).",
         "YES", "HIGH"),
    ]

    # Specific quick conversion reference guides (35 more)
    quick_conversions = [
        ("Meters to Feet Conversion: Fast Mental Math and Exact Multipliers", "meters to feet conversion"),
        ("Feet to Inches Conversion: Step-by-Step Multiplication Guide", "feet to inches conversion"),
        ("Inches to Centimeters Conversion: Exact 2.54 Multiplication Rule", "inches to cm conversion"),
        ("Kilometers to Miles Conversion: Using the Fibonacci Shortcut", "km to miles conversion"),
        ("Miles to Kilometers Conversion: The 1.6 Multiplier Guide", "miles to km conversion"),
        ("Centimeters to Inches Conversion: Division vs Multiplication Shortcuts", "cm to inches conversion"),
        ("Square Feet to Square Yards (Gaj) in Indian Real Estate", "sq ft to gaj conversion"),
        ("Square Feet to Square Meters: Exact Conversion for Floor Plans", "sq ft to sq meters conversion"),
        ("Acres to Hectares Conversion: Agriculture and Land Survey Math", "acres to hectares conversion"),
        ("Hectares to Acres Conversion: Step-by-Step Calculation", "hectares to acres conversion"),
        ("Bigha to Acre: State-Wise Conversion Variations Across North India", "bigha to acre conversion"),
        ("Guntha to Square Feet: Maharashtra, Gujarat, and Karnataka Real Estate Math", "guntha to sq ft conversion"),
        ("Kilograms to Pounds: Fast Gym Weight Conversion Guide", "kg to lbs conversion"),
        ("Pounds to Kilograms: Division by 2.2 Mental Math Trick", "lbs to kg conversion"),
        ("Grams to Ounces: Precision Kitchen Baking Conversion", "grams to ounces conversion"),
        ("Ounces to Grams: Exact 28.35 Multiplication Rule", "ounces to grams conversion"),
        ("Metric Tons to Kilograms: Understanding Bulk Cargo Weights", "metric tons to kg"),
        ("Milligrams to Grams: Pharmaceutical Dosage Conversion", "mg to grams conversion"),
        ("Celsius to Fahrenheit: The Double and Add 30 Mental Estimate", "celsius to fahrenheit conversion"),
        ("Fahrenheit to Celsius: Step-by-Step Subtraction and Division", "fahrenheit to celsius conversion"),
        ("Celsius to Kelvin: The 273.15 Constant in Chemistry Labs", "celsius to kelvin conversion"),
        ("Kilometers per Hour to Miles per Hour: Highway Speed Limit Math", "kmph to mph conversion"),
        ("Miles per Hour to Kilometers per Hour: Global Driving Guide", "mph to kmph conversion"),
        ("Meters per Second to Kilometers per Hour: The 18/5 Physics Rule", "mps to kmph conversion"),
        ("Gigabytes to Megabytes: Why 1024 Matters in File Transfer", "gb to mb conversion"),
        ("Terabytes to Gigabytes: Hard Drive and Cloud Storage Sizing", "tb to gb conversion"),
        ("Megabytes to Kilobytes: Document and Image Optimization Math", "mb to kb conversion"),
        ("Liters to Milliliters: Fast Decimal Multiplication Guide", "liters to ml conversion"),
        ("Liters to Gallons: Fuel Tank Capacity Conversion", "liters to gallons conversion"),
        ("Cubic Meters to Liters: Water Tank Capacity Calculation", "cubic meters to liters"),
        ("Bar to PSI: Tire Pressure Gauge Conversion Table", "bar to psi conversion"),
        ("PSI to Bar: Setting Accurate Vehicle Tire Pressures", "psi to bar conversion"),
        ("Kilowatts to Horsepower: Automotive Engine Power Math", "kw to hp conversion"),
        ("Horsepower to Kilowatts: Industrial Motor Power Ratings", "hp to kw conversion"),
        ("Joules to Calories: Food Energy vs Scientific Heat Transfer", "joules to calories conversion"),
    ]
    for title, kw in quick_conversions:
        unit_data.append((
            title, "Formula Guide", "Educational", kw,
            f"{kw} formula, how to calculate {kw}, exact {kw} table",
            "Unit Converter", "/calculators/unit-converter",
            f"Provide exact mathematical conversion factors, algebraic formulas, mental math shortcuts, and practical everyday examples for {kw}.",
            "YES", "HIGH" if "sq ft" in kw or "kg to lbs" in kw or "celsius" in kw or "meters to feet" in kw else "MEDIUM"
        ))

    for item in unit_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "Unit Conversion",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 4. Date & Calendar Calculations (20 topics)
    # Related Tool: Date Calculator (/calculators/date)
    # -------------------------------------------------------------
    date_data = [
        ("How to Calculate Exact Days Between Two Dates: The Mathematics of Calendar Intervals",
         "Formula Guide", "How-To", "how to calculate days between two dates",
         "date difference formula, days between dates calculation, calendar math formula",
         "Date Calculator", "/calculators/date",
         "Explain the algorithm: accounting for unequal month lengths (28, 30, 31 days), leap years, and whether start and end dates are inclusive or exclusive.",
         "YES", "HIGH"),
        ("How to Calculate Business Days (Working Days) Between Two Dates Excluding Weekends and Holidays",
         "How-To", "How-To", "how to calculate business days between two dates",
         "working days calculator formula, networkdays formula excel, exclude weekends and public holidays",
         "Date Calculator", "/calculators/date",
         "Formula: Total Days - (Full Weeks * 2) - Intersecting Weekend Days - Gazette Holidays. Show worked timeline examples for project deadlines.",
         "YES", "HIGH"),
        ("How to Add or Subtract Days from a Specific Date: Project Deadline Math",
         "How-To", "How-To", "how to add days to a date",
         "calculate future date by adding days, date plus 30 days formula, subtracting days from date",
         "Date Calculator", "/calculators/date",
         "Walk through carrying days across month boundaries, year-end rollovers, and leap-year transitions to pinpoint exact future milestone dates.",
         "YES", "HIGH"),
        ("Why Do Calendar Days and Working Days Produce Vastly Different Project Durations?",
         "Comparison", "Educational", "calendar days vs working days difference",
         "why working days are longer than calendar days, 30 calendar days in working weeks, project management date math",
         "Date Calculator", "/calculators/date",
         "Demonstrate that a '30-day' timeline means 6 calendar weeks (42 calendar days) when accounting for standard 5-day corporate working weeks.",
         "YES", "HIGH"),
        ("The Math of Leap Years: Why Century Years Like 1900 Were Not Leap Years But 2000 Was",
         "Explanation", "Educational", "why 1900 was not a leap year",
         "gregorian calendar leap year rule, century leap year rule 400, solar year duration math",
         "Date Calculator", "/calculators/date",
         "Explain solar orbital duration (365.2422 days) and why the Gregorian reform adds a leap day every 4 years, skips century years, but keeps quadricentennial centuries.",
         "YES", "HIGH"),
        ("How to Calculate Notice Period Completion Date in Corporate Resignations",
         "Guide", "How-To", "how to calculate notice period last working day",
         "last working day calculation formula, 90 days notice period calendar math, serving notice period rules",
         "Date Calculator", "/calculators/date",
         "Explain HR conventions: 30, 60, or 90 calendar days from the formal resignation email date, including public holidays and weekends.",
         "YES", "HIGH"),
        ("How to Calculate Warranty Expiry Date: 1 Year vs 365 Days vs Calendar Month Rules",
         "Guide", "Reference", "how warranty expiration date is calculated",
         "warranty date calculation consumer law, leap year warranty expiry, purchase date to warranty end",
         "Date Calculator", "/calculators/date",
         "Clarify consumer legal standards: whether a 1-year warranty expires on the preceding day of the next year (e.g. Nov 15 to Nov 14) and leap year adjustments.",
         "YES", "MEDIUM"),
        ("How Many Days in a Month: The Knuckle Method and Linguistic Rhymes Explained",
         "Guide", "Educational", "knuckle method days in month",
         "thirty days hath september rhyme, remembering days in month, month length memory tricks",
         "Date Calculator", "/calculators/date",
         "Explain the traditional knuckle mnemonic (knuckles = 31 days, depressions = 30 or 28/29 days) and its exact correspondence to the 12 calendar months.",
         "YES", "LOW"),
        ("How to Calculate Exact Weeks and Remaining Days Between Two Dates",
         "Formula Guide", "How-To", "how to calculate weeks between two dates",
         "weeks and days formula, convert days into weeks, integer division calendar math",
         "Date Calculator", "/calculators/date",
         "Formulas: Full Weeks = floor(Total Days / 7), Remaining Days = Total Days modulo 7. Work through pregnancy, fitness challenge, and semester timetables.",
         "YES", "HIGH"),
        ("How to Calculate the Date Exactly 90 Days (or 180 Days) from Today",
         "How-To", "How-To", "what date will it be in 90 days",
         "date 90 days from today calculation, 3 months vs 90 days date difference, visa validity 90 days",
         "Date Calculator", "/calculators/date",
         "Explain why '90 days' is NOT identical to '3 months' because three consecutive months contain 90, 91, or 92 days depending on the calendar quarter.",
         "YES", "HIGH"),
        ("How to Calculate Interest Days in Banking: The 30/360 vs Actual/365 Day Count Conventions",
         "Explanation", "Reference", "day count conventions 30 360 vs actual 365",
         "how banks count days for interest, bond day count convention, financial calendar math",
         "Date Calculator", "/calculators/date",
         "Explain international financial standards: 30/360 (assuming 30-day months) vs Actual/365 used by Indian commercial banks for daily interest calculations.",
         "YES", "MEDIUM"),
        ("How to Calculate Your Age in Weeks, Months, and Days Simultaneously",
         "How-To", "How-To", "convert age to total weeks",
         "age in weeks and days calculator, total weeks lived math, date of birth in weeks",
         "Date Calculator", "/calculators/date",
         "Provide multi-unit date decomposition formulas, showing step-by-step conversions without rounding drift.",
         "YES", "MEDIUM"),
        ("How Julian Day Numbers (JDN) Simplify Astronomical and Scientific Date Difference Math",
         "Explanation", "Educational", "what is julian day number in date calculation",
         "julian day formula astronomy, continuous count of days, date calculation algorithms",
         "Date Calculator", "/calculators/date",
         "Explain how astronomers and software engineers convert complex calendar dates into a continuous integer serial day count to subtract dates instantly.",
         "YES", "LOW"),
        ("Calculating Passport and Visa Validity: The 6-Month Passport Rule Explained",
         "Guide", "Reference", "6 month passport validity rule calculation",
         "calculating passport expiry for international travel, visa validity date difference, travel date calculation",
         "Date Calculator", "/calculators/date",
         "Explain international immigration requirements: calculating whether passport expiration is at least 180 days past intended departure date.",
         "YES", "HIGH"),
        ("How to Calculate Tenancy Agreement Renewal Dates and Lock-In Periods",
         "Guide", "How-To", "11 month rent agreement date calculation",
         "why rental agreement is 11 months, calculating lock in period expiry, lease renewal date calculation",
         "Date Calculator", "/calculators/date",
         "Explain the 11-month lease convention in India (avoiding Registration Act stamp duty) and calculating exact lock-in and notice period dates.",
         "YES", "HIGH"),
        ("How to Calculate Total Sundays or Specific Weekdays in a Given Month or Year",
         "Formula Guide", "How-To", "how to count number of sundays in a month",
         "counting specific weekdays between dates, calendar distribution of days, weekday frequency formula",
         "Date Calculator", "/calculators/date",
         "Provide mathematical algorithm to determine whether a month has 4 or 5 occurrences of a specific day based on month length and start weekday.",
         "YES", "MEDIUM"),
        ("How Fixed-Term Contract Expiration Dates Are Calculated in Indian Law",
         "Guide", "Reference", "fixed term contract expiry date rules",
         "contract end date calculation, employment contract renewal notice date, fixed term tenure math",
         "Date Calculator", "/calculators/date",
         "Review legal principles under General Clauses Act: when a deadline lands on a public holiday, does expiration extend to the next working day?",
         "YES", "LOW"),
        ("How to Calculate Date of Conception from Estimated Due Date (EDD) Using Naegele's Rule",
         "Formula Guide", "Reference", "naegele rule edd calculation",
         "pregnancy due date formula, calculate conception date from lmp, gestational calendar calculation",
         "Date Calculator", "/calculators/date",
         "Formula: EDD = First Day of Last Menstrual Period (LMP) + 1 Year - 3 Months + 7 Days. Work through pregnancy milestone calculations.",
         "YES", "HIGH"),
        ("How to Find the Day of the Week for Any Date in History: Doomsday Rule",
         "Guide", "How-To", "doomsday rule mental math for weekdays",
         "how to calculate day of week in head, john conway doomsday algorithm, calendar mental math",
         "Date Calculator", "/calculators/date",
         "Teach mathematician John Conway's famous Doomsday algorithm using anchor days (4/4, 6/6, 8/8, 10/10, 12/12) to determine weekdays mentally in 10 seconds.",
         "YES", "HIGH"),
        ("Summary Guide: Essential Formulas for Date Differences, Business Days, and Calendar Algorithms",
         "Formula Guide", "Reference", "date calculation formulas summary",
         "all date math formulas cheat sheet, business days formula, calendar algorithm reference",
         "Date Calculator", "/calculators/date",
         "Consolidated reference sheet covering calendar date intervals, leap year logic, Zeller's congruence, working day deduction formulas, and Naegele's rule.",
         "YES", "HIGH"),
    ]

    for item in date_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "Date",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 5. Discount & Savings (20 topics)
    # Related Tool: Discount Calculator (/calculators/discount)
    # -------------------------------------------------------------
    disc_data = [
        ("How to Calculate Discount Percentage and Sale Price: The Complete Math Guide",
         "Formula Guide", "How-To", "how to calculate discount percentage",
         "discount formula, sale price calculation formula, savings amount formula, shopping discount calculation",
         "Discount Calculator", "/calculators/discount",
         "Derive formulas: Discount Amount = Original Price * (Discount% / 100), Final Sale Price = Original Price - Discount Amount. Provide worked shopping examples.",
         "YES", "HIGH"),
        ("Successive Discounts Formula: Why 'Buy 50% + 50% Off' Does Not Mean Free",
         "Explanation", "Educational", "successive discount formula 50 plus 50",
         "why 50 plus 50 is not 100 percent discount, consecutive discount math, chain discount formula",
         "Discount Calculator", "/calculators/discount",
         "Prove mathematically that successive 50% + 50% yields a 75% net discount (0.50 * 0.50 = 0.25). General formula: d_net = d1 + d2 - (d1 * d2 / 100).",
         "YES", "HIGH"),
        ("Reverse Discount Calculation: How to Find the Original Price Before the Discount",
         "Formula Guide", "How-To", "how to find original price before discount",
         "reverse discount formula, calculate mrp from sale price, finding original price after discount",
         "Discount Calculator", "/calculators/discount",
         "Formula: Original Price = Sale Price / (1 - Discount% / 100). Address the common consumer error of adding the discount percentage back to the sale price.",
         "YES", "HIGH"),
        ("'Buy 2 Get 1 Free' vs 'Buy 3 Get 2 Free': What Is the Actual Percentage Discount?",
         "Comparison", "Educational", "actual discount on buy 2 get 1 free",
         "buy 1 get 1 free percentage discount, buy 2 get 1 free discount percentage, bogo offer math",
         "Discount Calculator", "/calculators/discount",
         "Formula: Discount % = [Free Items / Total Items Taken] * 100. Prove Buy 1 Get 1 = 50%, Buy 2 Get 1 Free = 33.33%, Buy 3 Get 2 Free = 40.0%.",
         "YES", "HIGH"),
        ("How to Calculate Cash Discount vs Trade Discount in Commercial Wholesale Invoices",
         "Comparison", "Reference", "trade discount vs cash discount",
         "difference between trade and cash discount, 2 10 net 30 discount formula, accounting for discounts",
         "Discount Calculator", "/calculators/discount",
         "Explain supply chain terms: Trade Discount (deducted from catalog price on invoice) vs Cash Discount (prompt payment discount like 2/10 Net 30).",
         "YES", "MEDIUM"),
        ("Flat Discount vs Percentage Discount: Which Offer Gives You a Better Deal?",
         "Comparison", "Comparison", "flat discount vs percentage discount",
         "flat 500 off vs 20 percent off, which discount saves more money, shopping discount comparison",
         "Discount Calculator", "/calculators/discount",
         "Calculate the breakeven spend threshold: e.g., Flat Rs 500 beats 20% on purchases under Rs 2,500, but 20% saves more on purchases above Rs 2,500.",
         "YES", "HIGH"),
        ("How to Calculate Additional Coupon Discounts and Bank Cashback Offers Together",
         "How-To", "How-To", "how to calculate stackable discounts and cashback",
         "coupon code plus bank discount calculation, credit card cashback on discounted price, total savings calculation",
         "Discount Calculator", "/calculators/discount",
         "Walk through multi-layer e-commerce checkout math: MRP -> Store Discount -> Coupon Code -> 10% Instant Bank Discount -> 5% Cashback.",
         "YES", "HIGH"),
        ("Markup vs Discount: Why a 25% Markup Followed by a 20% Discount Returns to Base",
         "Explanation", "Educational", "markup vs discount relationship",
         "why 25 markup and 20 discount is original price, markup percentage formula, cost price to mrp math",
         "Discount Calculator", "/calculators/discount",
         "Prove algebraically why Cost Price * 1.25 * 0.80 = Cost Price. Explain the mathematical duality between markup on cost and discount on selling price.",
         "YES", "HIGH"),
        ("How Retailers Inflate MRP Before Sales to Fake Big 70% Discounts",
         "Explanation", "Informational", "fake discounts during festival sales",
         "inflating mrp before discount, truth behind big billion days discounts, price tracking sale offers",
         "Discount Calculator", "/calculators/discount",
         "Expose psychological pricing: how artificial MRP inflation creates the illusion of 70% savings while net price remains unchanged, and how to verify real price history.",
         "YES", "HIGH"),
        ("Discount Calculation When Tax (GST) Is Applied After the Discount",
         "Formula Guide", "How-To", "how to calculate discount before gst",
         "gst on discounted price formula, does discount apply before tax, restaurant bill discount and gst",
         "Discount Calculator", "/calculators/discount",
         "Clarify the legal tax rule: GST is legally chargeable only on the net discounted transaction value (Sale Price), NOT on the original undiscounted MRP.",
         "YES", "HIGH"),
    ]

    # Specific quick discount percentage calculations (10 more)
    quick_discounts = [
        (10, 1000, "10% Off Rs 1,000: Quick Calculation and Savings Breakdown", "10 percent off 1000"),
        (15, 2000, "15% Off Rs 2,000: Sale Price and Exact Money Saved", "15 percent off 2000"),
        (20, 1500, "20% Off Rs 1,500: The Fast Division-by-5 Mental Shortcut", "20 percent off 1500"),
        (25, 4000, "25% Off Rs 4,000: Quarter-Price Reduction Calculation", "25 percent off 4000"),
        (30, 2500, "30% Off Rs 2,500: Mental Math Multiplication Technique", "30 percent off 2500"),
        (40, 5000, "40% Off Rs 5,000: Step-by-Step Sale Price Breakdown", "40 percent off 5000"),
        (50, 3000, "50% Off Rs 3,000: Half-Price Shopping Math and Savings", "50 percent off 3000"),
        (60, 8000, "60% Off Rs 8,000: Clearance Sale Price and Net Payment", "60 percent off 8000"),
        (70, 10000, "70% Off Rs 10,000: Heavy Clearance Discount Calculation", "70 percent off 10000"),
        (75, 12000, "75% Off Rs 12,000: Paying Exactly One-Fourth of MRP", "75 percent off 12000"),
    ]
    for pct, mrp, title, kw in quick_discounts:
        disc_data.append((
            title, "Example", "Educational", kw,
            f"how much is {pct} percent off {mrp}, sale price for {mrp} with {pct} discount, savings on {pct} percent off",
            "Discount Calculator", "/calculators/discount",
            f"Provide exact step-by-step mathematical calculations for a {pct}% discount on an item originally priced at Rs {mrp:,}, calculating exact savings and final checkout amount.",
            "YES", "HIGH" if pct in [10, 20, 25, 50] else "MEDIUM"
        ))

    for item in disc_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "Discount",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 6. Profit and Loss (15 topics)
    # Related Tool: Profit and Loss Calculator (/calculators/profit-loss)
    # -------------------------------------------------------------
    pl_data = [
        ("Profit and Loss Formulas: Cost Price (CP), Selling Price (SP), and Margin Calculation",
         "Formula Guide", "How-To", "profit and loss formula",
         "cost price selling price formula, profit percentage formula, loss percentage calculation",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Formulas: Profit = SP - CP, Loss = CP - SP. Profit % = (Profit / CP) * 100, Loss % = (Loss / CP) * 100. Explain why Cost Price is always the base denominator.",
         "YES", "HIGH"),
        ("Profit Percentage vs Profit Margin: Understanding the Critical Business Difference",
         "Comparison", "Educational", "profit percentage vs profit margin",
         "markup vs margin formula, gross margin vs profit on cost, difference between markup and margin",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Contrast Profit Percentage (Markup = Profit / Cost Price) with Profit Margin (Margin = Profit / Selling Price). Show why a 25% markup equals a 20% margin.",
         "YES", "HIGH"),
        ("How to Calculate Selling Price Given Cost Price and Desired Profit Percentage",
         "Formula Guide", "How-To", "how to calculate selling price with profit percentage",
         "selling price formula, sp from cp and profit percent, pricing product for target profit",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Formula: SP = CP * (1 + Profit% / 100). Step-by-step worked examples for retail merchandise and freelance service pricing.",
         "YES", "HIGH"),
        ("How to Calculate Cost Price Given Selling Price and Loss Percentage",
         "Formula Guide", "How-To", "how to calculate cost price from selling price and loss",
         "cost price formula when loss is given, cp from sp and loss percent, reverse cost price calculation",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Formula: CP = SP / (1 - Loss% / 100). Address the classic student fallacy of simply adding the loss percentage to the selling price.",
         "YES", "HIGH"),
        ("Break-Even Point (BEP) Formula: How Many Units Must You Sell to Cover Costs?",
         "Formula Guide", "Educational", "break even point calculation formula",
         "bep in units formula, fixed cost vs variable cost, break even analysis business",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Formula: BEP (units) = Fixed Costs / (Selling Price per Unit - Variable Cost per Unit). Explain contribution margin and financial break-even.",
         "YES", "HIGH"),
        ("Dishonest Dealer Problems: How False Weights and Measure Manipulation Generate Illicit Profit",
         "Explanation", "Educational", "dishonest dealer profit formula",
         "false weight profit percentage formula, cheating dealer math aptitude, error weight profit",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Formula: Gain % = [Error / (True Value - Error)] * 100. Solve classic quantitative aptitude problems where a merchant sells 900g for the price of 1,000g.",
         "YES", "HIGH"),
        ("Selling Two Items at the Same Price: One at a Profit and One at an Equal Loss",
         "Explanation", "Educational", "two items sold at same price profit and loss formula",
         "always loss formula sp same, common loss percentage (x/10)^2, quantitative aptitude profit loss trick",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Prove mathematically why selling two items at equal selling price with $x\%$ profit and $x\%$ loss always results in an overall net loss of $(x/10)^2$ percent.",
         "YES", "HIGH"),
        ("Gross Profit vs Net Profit: Operating Expenses and Bottom-Line Reality",
         "Comparison", "Educational", "gross profit vs net profit difference",
         "ebitda vs net profit, operating profit margin formula, calculating bottom line profit",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Compare Gross Profit (Revenue minus COGS) with Net Profit (after deducting salaries, rent, depreciation, interest, and corporate income taxes).",
         "YES", "HIGH"),
        ("How Overhead Costs (Shipping, Packaging, Marketing) Shift Your True Cost Price",
         "Guide", "How-To", "how to calculate true cost price with overheads",
         "cogs calculation ecommerce, factoring shipping into cost price, landed cost formula",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Formula: Effective CP = Raw Material + Labor + Packaging + Shipping + Payment Gateway Fees. Show why ignoring overheads leads to phantom profits.",
         "YES", "HIGH"),
        ("Loss Leader Pricing Strategy: Why Companies Deliberately Sell at a Loss",
         "Explanation", "Informational", "loss leader pricing strategy examples",
         "selling below cost price business strategy, razor and blade pricing model, why supermarkets sell at loss",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Explain retail economics: selling printers, gaming consoles, or staple groceries at a loss to monetize recurring cartridges, games, or high-margin basket items.",
         "YES", "MEDIUM"),
        ("How to Calculate Profit or Loss When Discount Is Offered on Marked Price (MRP)",
         "Formula Guide", "How-To", "profit and loss with discount and marked price",
         "relationship between cp sp and marked price, discount on mrp profit formula, markup discount profit math",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Derive the composite formula: $CP \\times (1 + \\text{Markup}\\%) \\times (1 - \\text{Discount}\\%) = SP$. Solve worked business problems.",
         "YES", "HIGH"),
        ("Return on Investment (ROI) vs Profit Margin: Evaluating Business Efficiency",
         "Comparison", "Educational", "roi vs profit margin comparison",
         "return on capital employed vs margin, business profitability metrics, roi formula",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Contrast Profit Margin (profit per rupee of revenue) with ROI (profit generated per rupee of invested capital), explaining capital efficiency.",
         "YES", "HIGH"),
        ("Understanding Dead Stock and Inventory Depreciation: When to Sell at a Loss",
         "Guide", "Planning", "when to liquidate inventory at a loss",
         "dead stock write off calculation, holding cost vs loss sale, inventory liquidation math",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Show mathematically why liquidating slow-moving inventory at a 20% loss frees up capital that yields 50% when reinvested into fast-moving stock.",
         "YES", "MEDIUM"),
        ("How to Build a Simple Profit and Loss Projection Spreadsheet for a Startup",
         "How-To", "How-To", "how to make profit and loss projection",
         "p&l statement template excel, forecasting revenue and expenses, monthly profit projection",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Step-by-step guide to setting up Revenue, Cost of Goods Sold, Gross Profit, Operating Expenses (Opex), and Net Profit before Tax.",
         "YES", "HIGH"),
        ("Summary Guide: Essential Formulas for Profit, Loss, Margins, and Markup",
         "Formula Guide", "Reference", "profit and loss formulas summary",
         "all profit loss formulas cheat sheet, cost price selling price reference, profit margin math summary",
         "Profit and Loss Calculator", "/calculators/profit-loss",
         "Consolidated reference sheet detailing formulas for Profit, Loss, Profit %, Loss %, Margin-to-Markup conversion, and Break-Even equations.",
         "YES", "HIGH"),
    ]

    for item in pl_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "Profit/Loss",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 7. Ratio & Proportion (15 topics)
    # Related Tool: Ratio Calculator (/calculators/ratio)
    # -------------------------------------------------------------
    ratio_data = [
        ("How to Simplify Ratios to Lowest Terms: The Greatest Common Divisor (GCD) Method",
         "Formula Guide", "How-To", "how to simplify ratios",
         "ratio simplifier formula, reducing ratios to lowest terms, gcd ratio reduction, simplify ratio step by step",
         "Ratio Calculator", "/calculators/ratio",
         "Explain the division algorithm: find the Greatest Common Divisor (GCD) of both terms and divide both sides. Provide worked examples (e.g. 48:72 -> 2:3).",
         "YES", "HIGH"),
        ("Ratio vs Proportion: Understanding the Core Mathematical Distinction",
         "Comparison", "Educational", "difference between ratio and proportion",
         "what is ratio and proportion, cross multiplication proportion, extreme and mean terms proportion",
         "Ratio Calculator", "/calculators/ratio",
         "Clarify the distinction: a ratio compares two quantities (a:b), while a proportion states that two ratios are equal (a:b = c:d), introducing Product of Extremes = Product of Means.",
         "YES", "HIGH"),
        ("How to Divide an Amount in a Given Ratio: Step-by-Step Practical Guide",
         "Formula Guide", "How-To", "how to divide money in a ratio",
         "sharing amount in ratio formula, dividing quantity in given ratio, ratio division step by step",
         "Ratio Calculator", "/calculators/ratio",
         "Formula: Share = Total Amount * (Part / Sum of Parts). Walk through dividing Rs 50,000 in the ratio 3:2:5 among business partners.",
         "YES", "HIGH"),
        ("Aspect Ratios in Screens and Video: 16:9, 4:3, 21:9, and 9:16 Dimensions Explained",
         "Guide", "Reference", "aspect ratio 16 9 calculation",
         "screen aspect ratio formula, 1920x1080 aspect ratio, convert resolution to aspect ratio",
         "Ratio Calculator", "/calculators/ratio",
         "Explain display resolutions: simplify 1920:1080 to 16:9, 3840:2160 (4K), vertical video 9:16 for reels/shorts, and ultrawide 21:9 monitors.",
         "YES", "HIGH"),
        ("How to Find the Missing Value in an Equivalent Ratio (Solving for X)",
         "Formula Guide", "How-To", "how to solve for x in ratio proportion",
         "missing value in ratio formula, cross multiplication ratio solver, finding x in proportion",
         "Ratio Calculator", "/calculators/ratio",
         "Solve a/b = c/x -> x = (b * c) / a. Work through concrete recipe scaling, construction mortar mix, and map scale problems.",
         "YES", "HIGH"),
        ("Direct Proportion vs Inverse (Indirect) Proportion: Formulas and Real-World Scenarios",
         "Comparison", "Educational", "direct vs inverse proportion",
         "indirect proportion formula, speed and time inverse proportion, direct variation examples",
         "Ratio Calculator", "/calculators/ratio",
         "Compare Direct Proportion (y = kx: more workers produce more goods) with Inverse Proportion (xy = k: higher speed takes less travel time).",
         "YES", "HIGH"),
        ("Gear Ratios and Mechanical Advantage: How Bicycle and Car Gears Work",
         "Explanation", "Educational", "gear ratio calculation formula",
         "how gear ratio is calculated, teeth count gear ratio, mechanical advantage ratio",
         "Ratio Calculator", "/calculators/ratio",
         "Formula: Gear Ratio = Driven Teeth / Driver Teeth. Explain high gear ratio (speed) vs low gear ratio (torque for hill climbing).",
         "YES", "MEDIUM"),
        ("Scale Factor in Architecture and Maps: How to Convert 1:100 Scale to Real Dimensions",
         "Guide", "How-To", "scale ratio conversion on architectural blueprints",
         "1 to 100 scale meaning, map scale ratio formula, calculating real distance from map scale",
         "Ratio Calculator", "/calculators/ratio",
         "Demonstrate multiplying blueprint measurements by the scale factor: 5 cm on a 1:100 drawing represents 500 cm (5 meters) in physical reality.",
         "YES", "HIGH"),
        ("How to Scale Cooking Recipes Up or Down Using Ingredient Ratios",
         "How-To", "How-To", "how to scale recipe ingredients using ratios",
         "recipe scaling factor formula, doubling recipe proportions, cooking ratio conversion",
         "Ratio Calculator", "/calculators/ratio",
         "Formula: Scale Factor = Desired Servings / Original Servings. Multiply all ingredients proportionally to maintain exact flavor and baking consistency.",
         "YES", "HIGH"),
        ("The Golden Ratio (1:1.618): Mathematical Definition and Occurrences in Art and Nature",
         "Explanation", "Educational", "what is golden ratio phi",
         "golden ratio formula 1.618, fibonacci sequence golden ratio, golden rectangle art design",
         "Ratio Calculator", "/calculators/ratio",
         "Derive Phi: $\phi = (1 + \sqrt{5}) / 2 \approx 1.618033$. Explore its emergence in Fibonacci limits, spiral shells, architecture, and UI layout proportions.",
         "YES", "MEDIUM"),
        ("How to Combine Two Separate Ratios: Merging a:b and b:c into a:b:c",
         "Formula Guide", "How-To", "how to combine two ratios a b and b c",
         "merging ratios formula, compound ratio calculation, 3 term ratio combining",
         "Ratio Calculator", "/calculators/ratio",
         "Find the Least Common Multiple (LCM) of the common term 'b' and scale both ratios accordingly to construct a unified 3-part ratio.",
         "YES", "HIGH"),
        ("Dilution Ratios in Chemistry and Cleaning Solutions: 1:10 vs 1 to 10 Explained",
         "Guide", "How-To", "how to calculate dilution ratio 1 to 10",
         "parts ratio dilution calculation, concentrated chemical dilution formula, chemical mixing ratio",
         "Ratio Calculator", "/calculators/ratio",
         "Clarify terminology: 1:10 dilution in chemistry means 1 part solute in 9 parts solvent (10 total parts) vs 1 part solute added to 10 parts solvent (11 parts).",
         "YES", "MEDIUM"),
        ("Debt-to-Income (DTI) and Debt-to-Equity Ratios: How Financial Health Is Measured",
         "Guide", "Reference", "financial ratios debt to equity and dti",
         "debt to income ratio calculation, corporate debt to equity ratio formula, solvency ratios",
         "Ratio Calculator", "/calculators/ratio",
         "Explain corporate and personal solvency ratios: total liabilities compared against income or shareholder equity to evaluate credit risk.",
         "YES", "HIGH"),
        ("Compressing Ratios: How to Convert Any Ratio (e.g. 17:43) to 1:N or N:1 Format",
         "Formula Guide", "How-To", "how to convert ratio to 1 to n format",
         "unit ratio calculation, normalizing ratio to 1, comparing unequal ratios",
         "Ratio Calculator", "/calculators/ratio",
         "Divide both terms by the first term (1 : b/a) or by the second term (a/b : 1) to enable intuitive comparisons between disparate data sets.",
         "YES", "HIGH"),
        ("Summary Guide: Key Formulas for Ratios, Proportions, Scaling, and Equivalent Reductions",
         "Formula Guide", "Reference", "ratio and proportion formulas summary",
         "all ratio formulas cheat sheet, proportion cross multiplication reference, ratio math guide",
         "Ratio Calculator", "/calculators/ratio",
         "Consolidated reference sheet detailing GCD simplification, Product of Extremes rule, 3-term ratio merging, and aspect ratio conversion formulas.",
         "YES", "HIGH"),
    ]

    for item in ratio_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "Ratio",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    # -------------------------------------------------------------
    # 8. Fractions & Operations (15 topics)
    # Related Tool: Fraction Calculator (/calculators/fraction)
    # -------------------------------------------------------------
    frac_data = [
        ("How to Add Fractions with Unlike Denominators: The Least Common Denominator (LCD) Method",
         "Formula Guide", "How-To", "how to add fractions with unlike denominators",
         "adding fractions formula, finding lcd of fractions, addition of fractions step by step",
         "Fraction Calculator", "/calculators/fraction",
         "Provide the 3-step method: 1) Find the Least Common Multiple (LCM) of denominators, 2) Convert numerators to equivalent fractions, 3) Add numerators and simplify.",
         "YES", "HIGH"),
        ("How to Subtract Fractions with Different Denominators: Complete Worked Examples",
         "Formula Guide", "How-To", "how to subtract fractions with different denominators",
         "subtracting fractions formula, fraction subtraction step by step, lcd fraction subtraction",
         "Fraction Calculator", "/calculators/fraction",
         "Step-by-step walkthrough of converting to common denominators, subtracting numerators, and reducing to lowest terms with positive and negative fractions.",
         "YES", "HIGH"),
        ("How to Multiply Fractions: Why You Multiply Numerators and Denominators Directly",
         "Formula Guide", "How-To", "how to multiply fractions",
         "multiplying fractions formula, cross canceling fractions before multiplying, fraction multiplication rule",
         "Fraction Calculator", "/calculators/fraction",
         "Formula: (a/b) * (c/d) = (a*c) / (b*d). Teach cross-simplification (canceling common factors) before multiplying to keep numbers small and manageable.",
         "YES", "HIGH"),
        ("How to Divide Fractions: Why You Invert and Multiply (Keep, Change, Flip)",
         "Formula Guide", "How-To", "how to divide fractions keep change flip",
         "dividing fractions formula, reciprocal of a fraction, why invert and multiply works",
         "Fraction Calculator", "/calculators/fraction",
         "Explain Keep, Change, Flip: Keep first fraction, Change division to multiplication, Flip second fraction into its reciprocal. Prove algebraically why multiplying by reciprocal divides.",
         "YES", "HIGH"),
        ("Proper vs Improper Fractions vs Mixed Numbers: Definitions and Conversions",
         "Comparison", "Educational", "improper fraction vs mixed number",
         "converting improper fraction to mixed number, proper fraction definition, mixed numbers explained",
         "Fraction Calculator", "/calculators/fraction",
         "Define terms: Proper (<1), Improper (>1), Mixed (Integer + Proper). Provide two-way conversion algorithms with worked examples.",
         "YES", "HIGH"),
        ("How to Convert Mixed Numbers to Improper Fractions: The Circle Method",
         "Formula Guide", "How-To", "convert mixed number to improper fraction formula",
         "mixed fraction to improper fraction, whole number times denominator plus numerator, converting mixed numbers",
         "Fraction Calculator", "/calculators/fraction",
         "Formula: Improper Numerator = (Whole Number * Denominator) + Numerator. Denominator stays unchanged. Walk through 3 2/5 -> 17/5.",
         "YES", "HIGH"),
        ("How to Convert Improper Fractions to Mixed Numbers: Division with Remainder",
         "Formula Guide", "How-To", "convert improper fraction to mixed number formula",
         "improper to mixed fraction division, quotient and remainder fraction, simplify improper fraction",
         "Fraction Calculator", "/calculators/fraction",
         "Formula: Whole Number = Quotient, New Numerator = Remainder, Denominator stays the same. Walk through 23/4 = 5 3/4.",
         "YES", "HIGH"),
        ("How to Simplify Fractions to Lowest Terms: Greatest Common Divisor (GCD)",
         "Formula Guide", "How-To", "how to simplify fractions to lowest terms",
         "reducing fractions formula, fraction simplifier step by step, gcd fraction simplification",
         "Fraction Calculator", "/calculators/fraction",
         "Explain finding prime factors or Euclidean GCD to divide both numerator and denominator by their greatest common factor.",
         "YES", "HIGH"),
        ("How to Compare Fractions: Cross-Multiplication Butterfly Method vs Common Denominator",
         "Comparison", "How-To", "how to compare fractions which is bigger",
         "butterfly method comparing fractions, cross multiplication fraction comparison, order fractions from least to greatest",
         "Fraction Calculator", "/calculators/fraction",
         "Teach the Butterfly method: to compare a/b vs c/d, compare cross-products (a*d) vs (b*c). If a*d > b*c, then a/b is greater.",
         "YES", "HIGH"),
        ("How to Convert Fractions to Decimals and Decimals to Fractions",
         "Formula Guide", "How-To", "how to convert fraction to decimal and decimal to fraction",
         "fraction to decimal long division, repeating decimals to fractions formula, converting decimals to lowest terms",
         "Fraction Calculator", "/calculators/fraction",
         "Explain long division for terminating decimals, and algebraic substitution for recurring repeating decimals (e.g. 0.333... = 1/3).",
         "YES", "HIGH"),
        ("How to Add and Subtract Mixed Numbers with Regrouping (Borrowing)",
         "Formula Guide", "How-To", "adding and subtracting mixed numbers with borrowing",
         "mixed fraction addition subtraction, regrouping whole numbers in fractions, borrowing from whole number fraction",
         "Fraction Calculator", "/calculators/fraction",
         "Explain borrowing: when subtracting 5 1/4 - 2 3/4, borrow 1 from 5 to convert into 4 5/4, then subtract easily.",
         "YES", "HIGH"),
        ("Multiplying and Dividing Mixed Numbers: Why Converting to Improper Fractions Is Mandatory",
         "Guide", "How-To", "how to multiply and divide mixed numbers",
         "multiplying mixed fractions step by step, why you must convert mixed numbers before dividing, mixed numbers operations",
         "Fraction Calculator", "/calculators/fraction",
         "Warn against the classic error of multiplying whole numbers and fractions separately; show why converting to improper fractions is mathematically necessary.",
         "YES", "HIGH"),
        ("Unit Fractions: Egyptian Fractions and Decomposing Rational Numbers",
         "Explanation", "Educational", "what are unit fractions and egyptian fractions",
         "egyptian fraction decomposition greedy algorithm, 1 over n fractions, unit fractions in math history",
         "Fraction Calculator", "/calculators/fraction",
         "Explain unit fractions (numerator 1) and how ancient Egyptians represented all rational fractions as sums of distinct unit fractions using greedy algorithms.",
         "YES", "LOW"),
        ("Continuous Fractions (Continued Fractions): How Irrational Numbers Are Approximated",
         "Explanation", "Educational", "what are continued fractions in mathematics",
         "continued fraction expansion pi, best rational approximations, golden ratio continued fraction",
         "Fraction Calculator", "/calculators/fraction",
         "Introduce continued fraction expansions $[a_0; a_1, a_2, \dots]$, showing why $22/7$ and $355/113$ provide extraordinarily accurate rational approximations of $\pi$.",
         "YES", "LOW"),
        ("Summary Guide: Complete Reference for Adding, Subtracting, Multiplying, and Dividing Fractions",
         "Formula Guide", "Reference", "fractions operations formulas summary",
         "all fraction formulas cheat sheet, lcd reciprocal mixed numbers reference, fraction math guide",
         "Fraction Calculator", "/calculators/fraction",
         "Consolidated reference sheet covering addition, subtraction, multiplication, division (Keep-Change-Flip), improper-mixed conversions, and GCD simplification.",
         "YES", "HIGH"),
    ]

    for item in frac_data:
        topics.append({
            "topic": item[0], "category": "General", "topic_cluster": "Fraction",
            "article_type": item[1], "search_intent": item[2], "primary_keyword": item[3],
            "secondary_keywords": item[4], "related_tool": item[5], "related_tool_slug": item[6],
            "content_angle": item[7], "evergreen": item[8], "priority": item[9]
        })

    return topics

if __name__ == "__main__":
    t = get_general_topics()
    print(f"Total General topics generated: {len(t)}")
