import type { Metadata } from 'next'
import { Breadcrumbs } from '../../components/Breadcrumbs'

export const metadata: Metadata = {
  title: 'Terms of Service | StudentTools',
  description:
    'Terms of service and usage conditions for the free educational and calculation platform StudentTools.cyou.',
  alternates: {
    canonical: 'https://www.studenttools.cyou/terms',
  },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50/50 pb-16">
      <div className="bg-white border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-6 pb-10">
          <Breadcrumbs items={[{ label: 'Terms of Service' }]} />
          <div className="mt-3">
            <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
              Terms of Service
            </h1>
            <p className="mt-2 text-sm text-slate-500">
              Last updated: September 2026 • Applicable to all visitors and users
            </p>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 mt-8 bg-white rounded-2xl border border-slate-200 p-6 sm:p-10 space-y-6 text-sm text-slate-700 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900">1. Acceptance of Terms</h2>
          <p>
            By accessing or using <strong>StudentTools</strong> (<code className="text-sky-600 font-mono">https://www.studenttools.cyou</code>), you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not use the website.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900">2. Informational & Educational Nature</h2>
          <p>
            The calculators, datasets, historical cutoff records, conversion charts, and estimates provided across StudentTools are provided strictly for <strong>educational, informational, and general planning purposes</strong>.
          </p>
          <p>
            None of the outputs generated by our calculators constitute official examination results, college admission commitments, financial or investment advisory, statutory legal counsel, or medical diagnoses.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900">3. User Responsibility & Verification</h2>
          <p>
            Users are solely responsible for verifying important academic requirements, university marks conversion policies, examination guidelines (with NTA or state authorities), and income tax calculations (with qualified professionals or the Income Tax Department) before making educational, career, or financial commitments.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900">4. Disclaimer of Warranties & Limitation of Liability</h2>
          <p>
            StudentTools provides all tools and services &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied. Under no circumstances shall StudentTools or its developers be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the platform.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900">5. Governing Law & Contact</h2>
          <p>
            These terms shall be governed by and construed in accordance with the laws of India. Inquiries regarding terms should be directed to <span className="font-mono text-slate-900">legal@studenttools.cyou</span>.
          </p>
        </section>
      </div>
    </div>
  )
}
